#!/usr/bin/env python3
"""Rasterize JetBrains Mono digit glyphs into an anti-aliased C bitmap font.

The DAQ HAT display (ESP32-C6) has no FPU, so rendering vector strokes per
frame is slow. This script bakes the glyphs we need for the measurement
readout (0-9, '.', '-', ' ') into 8-bit alpha bitmaps once, offline. The
firmware loads them into sprites at boot and just blits (cheap).

Source font: DesktopApp/BugBuster/public/fonts/jetbrains-mono-latin-wght-normal.woff2
Output:      Firmware/DAQ_HAT/ESP32C6/src/font_jbmono.c

Run from the repo root:  python Firmware/DAQ_HAT/tools/gen_font.py
"""
import io
import os
import sys

from fontTools.ttLib import TTFont
from PIL import Image, ImageFont, ImageDraw

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
WOFF2 = os.path.join(REPO, "DesktopApp", "BugBuster", "public", "fonts",
                     "jetbrains-mono-latin-wght-normal.woff2")
OUT = os.path.join(REPO, "Firmware", "DAQ_HAT", "ESP32C6", "src", "font_jbmono.c")

# Glyphs we render. Index order is fixed and mirrored by the firmware.
GLYPHS = "0123456789.- "

# Pixel height we rasterize at. Chosen so the cropped digit height fills the
# card's number band; the firmware blits 1:1 (no scaling).
PIXEL_SIZE = 36


def woff2_to_ttf_bytes(path: str) -> bytes:
    f = TTFont(path)  # fontTools auto-decompresses woff2 (needs brotli)
    buf = io.BytesIO()
    f.flavor = None
    f.save(buf)
    return buf.getvalue()


def main():
    if not os.path.exists(WOFF2):
        sys.exit(f"font not found: {WOFF2}")

    ttf = woff2_to_ttf_bytes(WOFF2)
    font = ImageFont.truetype(io.BytesIO(ttf), PIXEL_SIZE)

    asc, desc = font.getmetrics()
    full_h = asc + desc
    adv = int(round(font.getlength("0")))  # monospace advance

    # Pass 1: render each glyph onto a full-height cell sharing one baseline.
    raw = []
    for ch in GLYPHS:
        bbox = font.getbbox(ch)
        img = Image.new("L", (adv, full_h), 0)
        d = ImageDraw.Draw(img)
        gx = (adv - (bbox[2] - bbox[0])) // 2 - bbox[0]
        d.text((gx, 0), ch, fill=255, font=font)
        raw.append((ch, img))

    # Compute the tight shared vertical crop box over ALL glyphs so they stay
    # baseline-aligned but carry no excess padding.
    y0, y1 = full_h, 0
    for ch, img in raw:
        bb = img.getbbox()
        if bb:
            y0 = min(y0, bb[1])
            y1 = max(y1, bb[3])
    cell_h = y1 - y0

    glyphs = []
    for ch, img in raw:
        crop = img.crop((0, y0, adv, y1))
        glyphs.append((ch, adv, cell_h, crop.tobytes()))

    with open(OUT, "w", newline="\n") as f:
        f.write("// AUTO-GENERATED by Firmware/DAQ_HAT/tools/gen_font.py — do not edit.\n")
        f.write("// JetBrains Mono digit glyphs (0-9 . - space) baked as 8-bit\n")
        f.write("// alpha bitmaps for the DAQ HAT readout. Loaded into sprites at boot.\n\n")
        f.write("#include \"font_jbmono.h\"\n\n")
        f.write(f"#define JB_CELL_H {cell_h}\n")
        f.write(f"#define JB_ADVANCE {adv}\n\n")

        for i, (ch, w, h, data) in enumerate(glyphs):
            name = f"jb_g{i}"
            f.write(f"// '{ch}'  {w}x{h}\n")
            f.write(f"static const uint8_t {name}[{w*h}] = {{\n")
            for row in range(h):
                vals = data[row*w:(row+1)*w]
                f.write("    " + ",".join(str(b) for b in vals) + ",\n")
            f.write("};\n\n")

        f.write("const jb_glyph_t gfx_jbmono[] = {\n")
        for i, (ch, w, h, data) in enumerate(glyphs):
            f.write(f"    {{ {w}, {h}, jb_g{i} }},  // '{ch}'\n")
        f.write("};\n\n")
        f.write(f"const int gfx_jbmono_count = {len(glyphs)};\n")
        f.write(f"const int gfx_jbmono_cell_h = {cell_h};\n")
        f.write(f"const int gfx_jbmono_advance = {adv};\n")

    total = sum(w*h for _, w, h, _ in glyphs)
    print(f"wrote {OUT}")
    print(f"  {len(glyphs)} glyphs, cell {adv}x{cell_h}, {total} bytes alpha")


if __name__ == "__main__":
    main()
