export const functionConstants = [
  ["FUNC_HIGH_IMP", "High impedance input/off state"],
  ["FUNC_VOUT", "Voltage output"],
  ["FUNC_IOUT", "Current output"],
  ["FUNC_VIN", "Voltage input"],
  ["FUNC_IIN_EXT_PWR", "Current input with external loop power"],
  ["FUNC_IIN_LOOP_PWR", "Current input with loop power"],
  ["FUNC_RES_MEAS", "Resistance measurement"],
  ["FUNC_DIN_LOGIC", "Logic digital input"],
  ["FUNC_DIN_LOOP", "Loop digital input"],
  ["FUNC_IOUT_HART", "HART current output"],
  ["FUNC_IIN_EXT_PWR_HART", "HART current input with external loop power"],
  ["FUNC_IIN_LOOP_PWR_HART", "HART current input with loop power"],
  ["HAT_RAIL_3V3_ADJ", "HAT adjustable 3.3 V rail"],
  ["HAT_RAIL_VADJ3", "HAT VADJ3 rail"],
  ["HAT_RAIL_VADJ4", "HAT VADJ4 rail"],
  ["HAT_LED_OFF", "HAT status LED off"],
  ["HAT_LED_RED", "HAT status LED red"],
  ["HAT_LED_GREEN", "HAT status LED green"],
  ["HAT_LED_BLUE", "HAT status LED blue"],
  ["HAT_LED_YELLOW", "HAT status LED yellow"],
  ["HAT_LED_CYAN", "HAT status LED cyan"],
  ["HAT_LED_MAGENTA", "HAT status LED magenta"],
  ["HAT_LED_WHITE", "HAT status LED white"],
];

export const apiDocs = [
  {
    id: "sleep",
    group: "Core",
    title: "bugbuster.sleep",
    signature: "bugbuster.sleep(ms)",
    summary: "Cooperative delay that keeps script cancellation responsive.",
    args: [{ name: "ms", detail: "Delay in milliseconds. Must be >= 0." }],
    returns: "None",
    raises: ["ValueError if ms is negative."],
    example: "import bugbuster\n\nbugbuster.sleep(250)\nprint('settled')",
  },
  {
    id: "channel",
    group: "Channels",
    title: "bugbuster.Channel",
    signature: "ch = bugbuster.Channel(channel)",
    summary: "Create a handle for one AD74416H channel.",
    args: [{ name: "channel", detail: "Zero-based channel index, 0..3." }],
    returns: "Channel object.",
    raises: ["ValueError if channel is outside 0..3."],
    example: "import bugbuster\n\nch0 = bugbuster.Channel(0)",
  },
  {
    id: "set_function",
    group: "Channels",
    title: "Channel.set_function",
    signature: "ch.set_function(func)",
    summary: "Set the channel function using one of the bugbuster.FUNC_* constants.",
    args: [{ name: "func", detail: "One of the exported FUNC_* constants." }],
    returns: "None",
    raises: ["ValueError for unknown function codes.", "OSError(EIO) if hardware application fails."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nch.set_function(bugbuster.FUNC_VOUT)",
  },
  {
    id: "set_voltage",
    group: "Channels",
    title: "Channel.set_voltage",
    signature: "ch.set_voltage(voltage, bipolar=False)",
    summary: "Drive a voltage-output channel to the requested voltage.",
    args: [
      { name: "voltage", detail: "Target voltage in volts." },
      { name: "bipolar", detail: "Optional bool, default False." },
    ],
    returns: "None",
    raises: ["OSError(EIO) if the firmware cannot apply the requested DAC value."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nch.set_function(bugbuster.FUNC_VOUT)\nch.set_voltage(2.5)",
  },
  {
    id: "read_voltage",
    group: "Channels",
    title: "Channel.read_voltage",
    signature: "volts = ch.read_voltage()",
    summary: "Read the current measured voltage for the channel.",
    returns: "float voltage in volts.",
    raises: ["OSError(ETIMEDOUT) if ADC readback times out."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nprint(ch.read_voltage())",
  },
  {
    id: "set_do",
    group: "Channels",
    title: "Channel.set_do",
    signature: "ch.set_do(value)",
    summary: "Set digital-output state for a channel configured as an output.",
    args: [{ name: "value", detail: "Truth value. True drives on, False drives off." }],
    returns: "None",
    raises: ["OSError(EBUSY) if the channel is not ready for digital output."],
    example: "import bugbuster\n\nch = bugbuster.Channel(1)\nch.set_do(True)",
  },
  {
    id: "i2c",
    group: "I2C",
    title: "bugbuster.I2C",
    signature: "i2c = bugbuster.I2C(sda_io, scl_io, *, freq=400000, pullups='external', supply=3.3, vlogic=3.3, allow_split_supplies=False)",
    summary: "Route two BugBuster IO terminals to the external I2C engine. Reuses one external controller and exposes `i2c.close()` so you can free it before configuring a different pin pair.",
    args: [
      { name: "sda_io / scl_io", detail: "Logical IO terminal numbers 1..12, not raw GPIOs." },
      { name: "freq", detail: "Bus frequency in Hz, default 400000." },
      { name: "pullups", detail: "'external', 'internal', or 'off'." },
      { name: "supply / vlogic", detail: "Requested target/device rail voltages. supply powers the bus/device rail; vlogic sets the logic level. supply must be <= 5.0 V." },
    ],
    returns: "I2C object.",
    raises: ["ValueError for invalid IOs, duplicate pins, invalid pullups, unsafe supply, existing-controller conflicts, or route setup failure."],
    example: "import bugbuster\n\ni2c = bugbuster.I2C(1, 2, freq=400000, pullups='external', supply=3.3, vlogic=3.3)",
  },
  {
    id: "i2c_close",
    group: "I2C",
    title: "I2C.close",
    signature: "i2c.close()",
    summary: "Release the shared external I2C controller so another pin pair can be configured.",
    returns: "None",
    raises: ["OSError(EIO) if the controller cannot be closed."],
    example: "i2c.close()",
  },
  {
    id: "i2c_scan",
    group: "I2C",
    title: "I2C.scan",
    signature: "devices = i2c.scan(start=0x08, stop=0x77, skip_reserved=True, timeout_ms=50)",
    summary: "Scan for responding 7-bit I2C device addresses.",
    returns: "list[int] of addresses.",
    raises: ["OSError(EIO) if the scan fails."],
    example: "print([hex(a) for a in i2c.scan()])",
  },
  {
    id: "i2c_writeto",
    group: "I2C",
    title: "I2C.writeto",
    signature: "i2c.writeto(addr, buf, timeout_ms=50)",
    summary: "Write bytes to a 7-bit I2C address.",
    args: [
      { name: "addr", detail: "7-bit device address." },
      { name: "buf", detail: "bytes, bytearray, or other readable buffer." },
    ],
    returns: "None",
    raises: ["OSError(EIO) if the transaction fails."],
    example: "i2c.writeto(0x48, bytes([0x00]))",
  },
  {
    id: "i2c_readfrom",
    group: "I2C",
    title: "I2C.readfrom",
    signature: "data = i2c.readfrom(addr, n, timeout_ms=50)",
    summary: "Read bytes from a 7-bit I2C address.",
    args: [{ name: "n", detail: "Number of bytes to read, 1..512." }],
    returns: "bytes",
    raises: ["ValueError if n is outside 1..512.", "OSError(ETIMEDOUT) if the transaction times out."],
    example: "raw = i2c.readfrom(0x48, 2)",
  },
  {
    id: "i2c_write_read",
    group: "I2C",
    title: "I2C.writeto_then_readfrom",
    signature: "data = i2c.writeto_then_readfrom(addr, wr_buf, rd_n, timeout_ms=50)",
    summary: "Perform a write-then-read I2C transaction.",
    args: [{ name: "rd_n", detail: "Number of response bytes, 1..512." }],
    returns: "bytes",
    raises: ["ValueError if rd_n is outside 1..512.", "OSError(EIO) if the transaction fails."],
    example: "chip_id = i2c.writeto_then_readfrom(0x76, bytes([0xD0]), 1)",
  },
  {
    id: "spi",
    group: "SPI",
    title: "bugbuster.SPI",
    signature: "spi = bugbuster.SPI(sck_io, *, mosi_io=None, miso_io=None, cs_io=None, freq=1000000, mode=0, supply=3.3, vlogic=3.3, allow_split_supplies=False)",
    summary: "Route BugBuster IO terminals to the external SPI engine. Reuses one external controller and exposes `spi.close()` so you can free it before configuring a different pin pair.",
    args: [
      { name: "sck_io", detail: "Required logical IO terminal 1..12." },
      { name: "mosi_io / miso_io / cs_io", detail: "Optional logical IO terminals 1..12 or None." },
      { name: "mode", detail: "SPI mode 0..3." },
    ],
    returns: "SPI object.",
    raises: ["ValueError for invalid IOs, mode, unsafe supply, or route setup failure."],
    example: "import bugbuster\n\nspi = bugbuster.SPI(1, mosi_io=2, miso_io=3, cs_io=4, freq=1000000)",
  },
  {
    id: "spi_close",
    group: "SPI",
    title: "SPI.close",
    signature: "spi.close()",
    summary: "Release the shared external SPI controller so another pin pair can be configured.",
    returns: "None",
    raises: ["OSError(EIO) if the controller cannot be closed."],
    example: "spi.close()",
  },
  {
    id: "spi_transfer",
    group: "SPI",
    title: "SPI.transfer",
    signature: "rx = spi.transfer(buf)",
    summary: "Run a full-duplex SPI transfer. RX length matches TX length.",
    args: [{ name: "buf", detail: "Readable buffer, 1..512 bytes." }],
    returns: "bytes",
    raises: ["ValueError if buffer is empty or larger than 512 bytes.", "OSError(EIO) if the transfer fails."],
    example: "jedec = spi.transfer(bytes([0x9F, 0x00, 0x00, 0x00]))",
  },
  {
    id: "http_get",
    group: "Network",
    title: "bugbuster.http_get",
    signature: "r = bugbuster.http_get(url, *, headers=None, timeout_ms=10000)",
    summary: "Issue an HTTP/HTTPS GET from the device.",
    returns: "Response attrtuple with r.status and r.body bytes.",
    raises: ["ValueError for invalid timeout.", "OSError(ECONNABORTED) on transport failure.", "KeyboardInterrupt if stopped after request returns."],
    example: "r = bugbuster.http_get('https://example.com')\nprint(r.status, r.body[:32])",
  },
  {
    id: "http_post",
    group: "Network",
    title: "bugbuster.http_post",
    signature: "r = bugbuster.http_post(url, body=b'', *, headers=None, timeout_ms=10000)",
    summary: "Issue an HTTP/HTTPS POST from the device.",
    returns: "Response attrtuple with r.status and r.body bytes.",
    raises: ["ValueError for invalid timeout.", "OSError(ECONNABORTED) on transport failure.", "KeyboardInterrupt if stopped after request returns."],
    example: "r = bugbuster.http_post('https://example.com', b'payload')\nprint(r.status)",
  },
  {
    id: "mqtt_publish",
    group: "Network",
    title: "bugbuster.mqtt_publish",
    signature: "bugbuster.mqtt_publish(topic, payload, host, *, port=1883, username=None, password=None)",
    summary: "Publish a single MQTT message from the device.",
    args: [
      { name: "topic", detail: "MQTT topic string." },
      { name: "payload", detail: "Readable bytes-like payload." },
      { name: "host", detail: "Broker hostname or IP." },
    ],
    returns: "None",
    raises: ["ValueError if port is outside 1..65535.", "OSError(ECONNABORTED) if publishing fails."],
    example: "bugbuster.mqtt_publish('bench/status', b'ok', '192.168.1.10')",
  },
  {
    id: "hat_status",
    group: "HAT",
    title: "bugbuster.hat_status",
    signature: "status = bugbuster.hat_status()",
    summary: "Return the ESP32 snapshot of HAT presence, UART health, firmware version, pins, SWD state, and v2 telemetry.",
    returns: "dict with detected, connected, fw_major/fw_minor, pin_config, degraded, and related status fields.",
    raises: ["OSError(EIO) if the HAT state is unavailable."],
    example: "import bugbuster\n\nstatus = bugbuster.hat_status()\nprint(status['detected'], status['connected'])",
  },
  {
    id: "hat_caps",
    group: "HAT",
    title: "bugbuster.hat_caps",
    signature: "caps = bugbuster.hat_caps()",
    summary: "Query HAT v2 capability metadata from the RP2040.",
    returns: "dict with hw_revision, flags, rail_count, led_count, shifted_io_count, la_routes, fw_major, fw_minor, hvpak_present.",
    raises: ["OSError(EIO) when no HAT is connected or the UART command fails."],
    example: "caps = bugbuster.hat_caps()\nprint(caps['rail_count'], caps['led_count'])",
  },
  {
    id: "hat_rails",
    group: "HAT",
    title: "bugbuster.hat_rails",
    signature: "rails = bugbuster.hat_rails()",
    summary: "Read HAT rail enable state, measured voltage, current, and fault status.",
    returns: "list[dict] with rail_id, enabled, voltage_mv, current_ma, status.",
    raises: ["OSError(EIO) when no HAT is connected or the rail status command fails."],
    example: "for rail in bugbuster.hat_rails():\n    print(rail['rail_id'], rail['voltage_mv'], rail['enabled'])",
  },
  {
    id: "hat_set_rail_enable",
    group: "HAT",
    title: "bugbuster.hat_set_rail_enable",
    signature: "bugbuster.hat_set_rail_enable(rail_id, enable)",
    summary: "Enable or disable a HAT v2 rail.",
    args: [{ name: "rail_id", detail: "0=3V3_ADJ, 1=VADJ3, 2=VADJ4." }, { name: "enable", detail: "Boolean output enable." }],
    returns: "None",
    raises: ["ValueError for invalid rail_id.", "OSError(EIO) if the HAT rejects the command."],
    example: "bugbuster.hat_set_rail_enable(bugbuster.HAT_RAIL_VADJ3, True)",
  },
  {
    id: "hat_set_rail_voltage",
    group: "HAT",
    title: "bugbuster.hat_set_rail_voltage",
    signature: "bugbuster.hat_set_rail_voltage(rail_id, voltage_mv)",
    summary: "Set a HAT adjustable rail target voltage in millivolts.",
    args: [{ name: "voltage_mv", detail: "Requested target in mV. Firmware/HAT enforce rail-specific safe ranges." }],
    returns: "None",
    raises: ["ValueError for invalid rail_id or voltage range.", "OSError(EIO) if the HAT rejects the command."],
    example: "bugbuster.hat_set_rail_voltage(bugbuster.HAT_RAIL_VADJ4, 5000)",
  },
  {
    id: "hat_led",
    group: "HAT",
    title: "bugbuster.hat_led",
    signature: "bugbuster.hat_led(led_id, color_code)",
    summary: "Set one of the eight HAT status LEDs.",
    args: [{ name: "led_id", detail: "1..8." }, { name: "color_code", detail: "Use HAT_LED_* constants or 0..255 raw code." }],
    returns: "None",
    raises: ["ValueError for invalid LED or color.", "OSError(EIO) if the command fails."],
    example: "bugbuster.hat_led(1, bugbuster.HAT_LED_GREEN)",
  },
  {
    id: "hat_io_bank",
    group: "HAT",
    title: "bugbuster.hat_io_bank",
    signature: "bugbuster.hat_io_bank(dirs, *, ups=0, dns=0, vals=0)",
    summary: "Configure the HAT shifted IO bank directions, pulls, and optional output values as bit masks.",
    args: [{ name: "dirs", detail: "Direction mask, 1=output." }, { name: "ups / dns / vals", detail: "Pull-up, pull-down, and output value masks." }],
    returns: "None",
    raises: ["ValueError if masks are outside 0..255.", "OSError(EIO) if the command fails."],
    example: "bugbuster.hat_io_bank(0b00001111, ups=0, dns=0, vals=0b00000101)",
  },
  {
    id: "hat_level_shift",
    group: "HAT",
    title: "bugbuster.hat_level_shift",
    signature: "state = bugbuster.hat_level_shift(oe, dir)",
    summary: "Override HAT level-shifter output-enable and direction pins.",
    returns: "dict with oe and dir fields reflecting the applied state.",
    raises: ["OSError(EIO) if the command fails."],
    example: "print(bugbuster.hat_level_shift(True, True))",
  },
  {
    id: "hat_calibrate_status",
    group: "HAT Calibration",
    title: "bugbuster.hat_calibrate_status",
    signature: "status = bugbuster.hat_calibrate_status()",
    summary: "Read HAT rail calibration sweep state and validation telemetry.",
    returns: "dict with state, progress, rail_id, last_error, stage, point, code, measured_mv, min/max/gap/error telemetry, validation_flags.",
    raises: ["OSError(EIO) if the command fails."],
    example: "print(bugbuster.hat_calibrate_status())",
  },
  {
    id: "hat_calibrate_start",
    group: "HAT Calibration",
    title: "bugbuster.hat_calibrate_start",
    signature: "state = bugbuster.hat_calibrate_start(rail_id)",
    summary: "Start HAT rail auto-calibration for VADJ3 or VADJ4.",
    returns: "Initial calibration state code.",
    raises: ["ValueError for invalid rail_id.", "OSError(EIO) if calibration cannot start."],
    example: "bugbuster.hat_calibrate_start(bugbuster.HAT_RAIL_VADJ3)",
  },
  {
    id: "hat_calibrate_import",
    group: "HAT Calibration",
    title: "bugbuster.hat_calibrate_import",
    signature: "bugbuster.hat_calibrate_import(rail_id, points)",
    summary: "Import 2..6 calibration points into the HAT. Each point is a `(dac_code, measured_v)` pair.",
    returns: "None",
    raises: ["ValueError for invalid rail or point list.", "OSError(EIO) if the HAT rejects the import."],
    example: "bugbuster.hat_calibrate_import(1, [(-8, 3.42), (0, 3.30), (8, 3.18)])",
  },
  {
    id: "hat_setup_swd",
    group: "HAT",
    title: "bugbuster.hat_setup_swd",
    signature: "bugbuster.hat_setup_swd(target_voltage_mv=3300, *, connector=0)",
    summary: "Run the ESP32 HAT SWD setup sequence for the dedicated CMSIS-DAP connector.",
    returns: "None",
    raises: ["ValueError for invalid voltage or connector.", "OSError(EIO) if setup fails."],
    example: "bugbuster.hat_setup_swd(3300, connector=0)",
  },
  {
    id: "bb_helpers_settle",
    group: "Helpers",
    title: "bb_helpers.settle",
    signature: "bb_helpers.settle(ms)",
    summary: "Cooperative delay. Alias for bugbuster.sleep(ms).",
    args: [{ name: "ms", detail: "Delay in milliseconds." }],
    returns: "None",
    example: "import bb_helpers\n\nbb_helpers.settle(100)",
  },
  {
    id: "bb_helpers_dac_ramp",
    group: "Helpers",
    title: "bb_helpers.dac_ramp",
    signature: "results = bb_helpers.dac_ramp(channel, lo, hi, step, settle_ms=50)",
    summary: "Ramp a channel to FUNC_VOUT from lo to hi V in step increments, reading back ADC at each step. Restores FUNC_HIGH_IMP on return.",
    args: [
      { name: "channel", detail: "Zero-based channel index, 0..3." },
      { name: "lo / hi", detail: "Start and end voltages in volts." },
      { name: "step", detail: "Voltage step in volts." },
      { name: "settle_ms", detail: "Settle time per step in ms, default 50." },
    ],
    returns: "list of (voltage, readback) float tuples.",
    example: "import bb_helpers\n\nresults = bb_helpers.dac_ramp(0, 0.0, 5.0, 1.0)\nfor v, rb in results:\n    print('set=%.2f read=%.5f' % (v, rb))",
  },
  {
    id: "bb_devices_tmp102",
    group: "Devices",
    title: "bb_devices.TMP102",
    signature: "sensor = bb_devices.TMP102(i2c, addr=0x48)",
    summary: "TI TMP102 I2C temperature sensor driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x48." },
    ],
    returns: "TMP102 instance.",
    example: "import bb_devices, bugbuster\n\ni2c = bugbuster.I2C(1, 2, freq=400000, pullups='external')\nsensor = bb_devices.TMP102(i2c)\nprint('%.2f C' % sensor.read_celsius())",
  },
  {
    id: "bb_devices_tmp102_read",
    group: "Devices",
    title: "TMP102.read_celsius",
    signature: "temp = sensor.read_celsius()",
    summary: "Read temperature from TMP102.",
    returns: "float degrees Celsius.",
    raises: ["OSError(EIO) if the I2C transaction fails."],
    example: "print('Temp: %.2f C' % sensor.read_celsius())",
  },
  {
    id: "bb_devices_bmp280",
    group: "Devices",
    title: "bb_devices.BMP280",
    signature: "bmp = bb_devices.BMP280(i2c, addr=0x76)",
    summary: "Bosch BMP280 I2C pressure/temperature sensor driver. Verifies chip ID on construction and sets normal mode (x1 oversampling).",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x76 (alt 0x77)." },
    ],
    returns: "BMP280 instance.",
    raises: ["OSError if chip ID does not match 0x60."],
    example: "import bb_devices, bugbuster\n\ni2c = bugbuster.I2C(1, 2, freq=400000, pullups='external')\nbmp = bb_devices.BMP280(i2c)\nt_raw, p_raw = bmp.read()\nprint('t=%d p=%d' % (t_raw, p_raw))",
  },
  {
    id: "bb_devices_bmp280_read",
    group: "Devices",
    title: "BMP280.read",
    signature: "(temp_raw, press_raw) = bmp.read()",
    summary: "Read uncompensated raw ADC values. Full compensation requires reading trimming params; this returns raw integers suitable for protocol demos.",
    returns: "tuple (temperature_raw, pressure_raw) as uncompensated integers.",
    raises: ["OSError(EIO) if the I2C transaction fails."],
    example: "t_raw, p_raw = bmp.read()",
  },
  {
    id: "bb_devices_mcp3008",
    group: "Devices",
    title: "bb_devices.MCP3008",
    signature: "adc = bb_devices.MCP3008(spi, channels=8)",
    summary: "Microchip MCP3008 SPI 10-bit ADC driver (4 or 8 channels).",
    args: [
      { name: "spi", detail: "bugbuster.SPI instance." },
      { name: "channels", detail: "4 or 8, default 8." },
    ],
    returns: "MCP3008 instance.",
    raises: ["ValueError if channels is not 4 or 8."],
    example: "import bb_devices, bugbuster\n\nspi = bugbuster.SPI(4, mosi_io=5, miso_io=6, cs_io=7, freq=1000000)\nadc = bb_devices.MCP3008(spi)\nraw = adc.read(0)\nprint('%.3f V' % (raw * 3.3 / 1023.0))",
  },
  {
    id: "bb_devices_mcp3008_read",
    group: "Devices",
    title: "MCP3008.read",
    signature: "raw = adc.read(channel, single_ended=True)",
    summary: "Read one MCP3008 channel. Returns a 10-bit value (0–1023).",
    args: [
      { name: "channel", detail: "Channel index 0 to channels-1." },
      { name: "single_ended", detail: "True for single-ended (default), False for differential." },
    ],
    returns: "int 0..1023.",
    raises: ["ValueError if channel is out of range."],
    example: "raw = adc.read(channel=0)\nvolts = raw * 3.3 / 1023.0",
  },
  {
    id: "bb_devices_ds18b20",
    group: "Devices",
    title: "bb_devices.DS18B20",
    signature: "sensor = bb_devices.DS18B20(pin)",
    summary: "Dallas DS18B20 OneWire temperature sensor driver. Requires machine.Pin, onewire, and ds18x20.",
    args: [{ name: "pin", detail: "ESP32 GPIO number or machine.Pin object for the OneWire data line." }],
    returns: "DS18B20 instance.",
    example: "import bb_devices\n\nsensor = bb_devices.DS18B20(2)\nprint(sensor.read_all())",
  },
  {
    id: "bb_devices_ds3231",
    group: "Devices",
    title: "bb_devices.DS3231",
    signature: "rtc = bb_devices.DS3231(i2c, addr=0x68)",
    summary: "Maxim DS3231 RTC with BCD datetime access and temperature readback.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x68." },
    ],
    returns: "DS3231 instance.",
    example: "rtc = bb_devices.DS3231(i2c)\nprint(rtc.read_datetime())",
  },
  {
    id: "bb_devices_bh1750",
    group: "Devices",
    title: "bb_devices.BH1750",
    signature: "light = bb_devices.BH1750(i2c, addr=0x23)",
    summary: "ROHM BH1750 ambient light sensor driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x23 (alt 0x5C)." },
    ],
    returns: "BH1750 instance.",
    example: "light = bb_devices.BH1750(i2c)\nprint('Lux: %.1f' % light.read_lux())",
  },
  {
    id: "bb_devices_aht20",
    group: "Devices",
    title: "bb_devices.AHT20",
    signature: "sensor = bb_devices.AHT20(i2c, addr=0x38)",
    summary: "Aosong AHT20 humidity and temperature sensor driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x38." },
    ],
    returns: "AHT20 instance.",
    example: "sensor = bb_devices.AHT20(i2c)\nprint(sensor.read())",
  },
  {
    id: "bb_devices_sht31",
    group: "Devices",
    title: "bb_devices.SHT31",
    signature: "sensor = bb_devices.SHT31(i2c, addr=0x44)",
    summary: "Sensirion SHT31 humidity and temperature sensor driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x44 (alt 0x45)." },
    ],
    returns: "SHT31 instance.",
    example: "sensor = bb_devices.SHT31(i2c)\nprint(sensor.read())",
  },
  {
    id: "bb_devices_bme280",
    group: "Devices",
    title: "bb_devices.BME280",
    signature: "sensor = bb_devices.BME280(i2c, addr=0x76)",
    summary: "Bosch BME280 compensated temperature, pressure, and humidity sensor driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x76 (alt 0x77)." },
    ],
    returns: "BME280 instance.",
    example: "sensor = bb_devices.BME280(i2c)\nprint(sensor.read())",
  },
  {
    id: "bb_devices_ina219",
    group: "Devices",
    title: "bb_devices.INA219",
    signature: "sensor = bb_devices.INA219(i2c, addr=0x40, shunt_ohms=0.1, max_expected_amps=2.0)",
    summary: "TI INA219 current, bus voltage, and power monitor.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x40." },
      { name: "shunt_ohms", detail: "Sense resistor value in ohms, default 0.1." },
      { name: "max_expected_amps", detail: "Used to derive the calibration value." },
    ],
    returns: "INA219 instance.",
    example: "sensor = bb_devices.INA219(i2c)\nprint(sensor.read())",
  },
  {
    id: "bb_devices_ads1115",
    group: "Devices",
    title: "bb_devices.ADS1115",
    signature: "adc = bb_devices.ADS1115(i2c, addr=0x48)",
    summary: "TI ADS1115 precision 16-bit ADC driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x48." },
    ],
    returns: "ADS1115 instance.",
    example: "adc = bb_devices.ADS1115(i2c)\nprint(adc.read_voltage(channel=0))",
  },
  {
    id: "bb_devices_mcp23017",
    group: "Devices",
    title: "bb_devices.MCP23017",
    signature: "gpio = bb_devices.MCP23017(i2c, addr=0x20)",
    summary: "Microchip MCP23017 16-bit GPIO expander with pin-level direction and pull-up helpers.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x20." },
    ],
    returns: "MCP23017 instance.",
    example: "gpio = bb_devices.MCP23017(i2c)\ngpio.pin_mode(0, output=True)\ngpio.set_pin(0, 1)",
  },
  {
    id: "bb_devices_mcp23017_pin_mode",
    group: "Devices",
    title: "MCP23017.pin_mode",
    signature: "gpio.pin_mode(pin, output=True, pullup=False)",
    summary: "Set one MCP23017 pin to input or output and optionally enable its internal pull-up.",
    args: [
      { name: "pin", detail: "Pin number 0..15." },
      { name: "output", detail: "True for output, False for input." },
      { name: "pullup", detail: "True to enable the internal pull-up." },
    ],
    returns: "None",
    raises: ["ValueError if pin is outside 0..15."],
    example: "gpio.pin_mode(0, output=True)\ngpio.pin_mode(1, output=False, pullup=True)",
  },
  {
    id: "bb_devices_mcp23017_set_dir",
    group: "Devices",
    title: "MCP23017.set_dir",
    signature: "gpio.set_dir(pin, output=True)",
    summary: "Set one MCP23017 pin direction.",
    args: [
      { name: "pin", detail: "Pin number 0..15." },
      { name: "output", detail: "True for output, False for input." },
    ],
    returns: "None",
    raises: ["ValueError if pin is outside 0..15."],
    example: "gpio.set_dir(0, output=True)",
  },
  {
    id: "bb_devices_mcp23017_set_pullup",
    group: "Devices",
    title: "MCP23017.set_pullup",
    signature: "gpio.set_pullup(pin, enable=True)",
    summary: "Enable or disable the internal pull-up for one MCP23017 pin.",
    args: [
      { name: "pin", detail: "Pin number 0..15." },
      { name: "enable", detail: "True to enable the pull-up." },
    ],
    returns: "None",
    raises: ["ValueError if pin is outside 0..15."],
    example: "gpio.set_pullup(1, enable=True)",
  },
  {
    id: "bb_devices_pcf8574",
    group: "Devices",
    title: "bb_devices.PCF8574",
    signature: "gpio = bb_devices.PCF8574(i2c, addr=0x20, value=0xFF)",
    summary: "NXP PCF8574 8-bit quasi-bidirectional GPIO expander.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x20." },
      { name: "value", detail: "Initial output byte, default 0xFF." },
    ],
    returns: "PCF8574 instance.",
    example: "gpio = bb_devices.PCF8574(i2c)\nprint(gpio.read())",
  },
  {
    id: "bb_devices_pca9685",
    group: "Devices",
    title: "bb_devices.PCA9685",
    signature: "pwm = bb_devices.PCA9685(i2c, addr=0x40, osc_hz=25000000)",
    summary: "NXP PCA9685 16-channel PWM controller.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x40." },
      { name: "osc_hz", detail: "Oscillator frequency in Hz, default 25 MHz." },
    ],
    returns: "PCA9685 instance.",
    example: "pwm = bb_devices.PCA9685(i2c)\npwm.set_duty(0, 0.10)",
  },
  {
    id: "bb_devices_tcs34725",
    group: "Devices",
    title: "bb_devices.TCS34725",
    signature: "sensor = bb_devices.TCS34725(i2c, addr=0x29)",
    summary: "ams OSRAM TCS34725 RGBC color sensor driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x29." },
    ],
    returns: "TCS34725 instance.",
    example: "sensor = bb_devices.TCS34725(i2c)\nprint(sensor.read_rgbc())",
  },
  {
    id: "bb_devices_mpu6050",
    group: "Devices",
    title: "bb_devices.MPU6050",
    signature: "imu = bb_devices.MPU6050(i2c, addr=0x68, accel_range=2, gyro_range=250)",
    summary: "InvenSense MPU6050 6-axis IMU driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x68." },
      { name: "accel_range / gyro_range", detail: "Full-scale ranges in g and dps." },
    ],
    returns: "MPU6050 instance.",
    example: "imu = bb_devices.MPU6050(i2c)\nprint(imu.read())",
  },
  {
    id: "bb_devices_mcp4725",
    group: "Devices",
    title: "bb_devices.MCP4725",
    signature: "dac = bb_devices.MCP4725(i2c, addr=0x60, vref=3.3)",
    summary: "Microchip MCP4725 12-bit I2C DAC driver.",
    args: [
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x60." },
      { name: "vref", detail: "Reference voltage used by set_voltage()." },
    ],
    returns: "MCP4725 instance.",
    example: "dac = bb_devices.MCP4725(i2c)\ndac.set_voltage(1.65)",
  },
  {
    id: "bb_devices_ssd1306",
    group: "Devices",
    title: "bb_devices.SSD1306",
    signature: "display = bb_devices.SSD1306(width, height, i2c, addr=0x3c)",
    summary: "SSD1306 OLED wrapper over the upstream MicroPython driver. Use the same API as ssd1306.SSD1306_I2C.",
    args: [
      { name: "width / height", detail: "Display geometry in pixels." },
      { name: "i2c", detail: "bugbuster.I2C instance." },
      { name: "addr", detail: "7-bit I2C address, default 0x3C." },
    ],
    returns: "SSD1306 display instance.",
    example: "display = bb_devices.SSD1306(128, 64, i2c)\ndisplay.text('BugBuster', 0, 0, 1)\ndisplay.show()",
  },
  {
    id: "bb_devices_ds18b20_read_celsius",
    group: "Devices",
    title: "DS18B20.read_celsius",
    signature: "temp = sensor.read_celsius(rom=None, wait_ms=750)",
    summary: "Start conversion and read temperature in Celsius for one DS18B20 sensor. If rom is None, reads the first available device.",
    args: [
      { name: "rom", detail: "Optional 8-byte ROM address (bytes)." },
      { name: "wait_ms", detail: "Delay in ms for conversion, default 750." },
    ],
    returns: "float degrees Celsius.",
    raises: ["OneWireError if conversion or read fails."],
    example: "temp = sensor.read_celsius()\nprint('Temp: %.2f C' % temp)",
  },
  {
    id: "bb_devices_ds18b20_read_all",
    group: "Devices",
    title: "DS18B20.read_all",
    signature: "results = sensor.read_all(wait_ms=750)",
    summary: "Perform a parallel temperature conversion and read all scanned DS18B20 devices.",
    args: [
      { name: "wait_ms", detail: "Delay in ms for conversion, default 750." },
    ],
    returns: "dict of ROM (bytes) -> float temperature.",
    example: "results = sensor.read_all()\nfor rom, temp in results.items():\n    print('%s: %.2f C' % (rom.hex(), temp))",
  },
  {
    id: "bb_devices_ds18b20_scan",
    group: "Devices",
    title: "DS18B20.scan",
    signature: "roms = sensor.scan()",
    summary: "Scan the OneWire bus for DS18B20 devices.",
    returns: "list of 8-byte ROM addresses (bytes).",
    example: "roms = sensor.scan()\nprint('Found %d devices' % len(roms))",
  },
  {
    id: "bb_devices_ds3231_read_datetime",
    group: "Devices",
    title: "DS3231.read_datetime",
    signature: "dt = rtc.read_datetime()",
    summary: "Read the current RTC date and time.",
    returns: "tuple: (year, month, mday, wday, hour, minute, second).",
    example: "dt = rtc.read_datetime()\nprint('Time: %02d:%02d:%02d' % (dt[4], dt[5], dt[6]))",
  },
  {
    id: "bb_devices_ds3231_set_datetime",
    group: "Devices",
    title: "DS3231.set_datetime",
    signature: "rtc.set_datetime(year, month, day, weekday, hour, minute, second)",
    summary: "Set the RTC date and time.",
    args: [
      { name: "year", detail: "Four-digit year (e.g. 2026)." },
      { name: "month", detail: "Month 1..12." },
      { name: "day", detail: "Day of the month 1..31." },
      { name: "weekday", detail: "Day of the week (1=Monday...7=Sunday)." },
      { name: "hour/minute/second", detail: "Time components." },
    ],
    returns: "None",
    example: "rtc.set_datetime(2026, 6, 12, 5, 16, 13, 0)",
  },
  {
    id: "bb_devices_ds3231_temperature_c",
    group: "Devices",
    title: "DS3231.temperature_c",
    signature: "temp = rtc.temperature_c()",
    summary: "Read the DS3231 internal compensated temperature sensor.",
    returns: "float temperature in Celsius.",
    example: "print('RTC Temp: %.2f C' % rtc.temperature_c())",
  },
  {
    id: "bb_devices_bh1750_read_lux",
    group: "Devices",
    title: "BH1750.read_lux",
    signature: "lux = light.read_lux(high_res=True, one_time=True, mtreg=69)",
    summary: "Read ambient light level in lux.",
    args: [
      { name: "high_res", detail: "If True, use 1.0 lx resolution, else 4.0 lx." },
      { name: "one_time", detail: "If True, power down sensor after measurement." },
      { name: "mtreg", detail: "Measurement time register value (default 69)." },
    ],
    returns: "float light level in lux.",
    example: "print('Lux: %.1f' % light.read_lux())",
  },
  {
    id: "bb_devices_aht20_read",
    group: "Devices",
    title: "AHT20.read",
    signature: "(temp, humidity) = sensor.read()",
    summary: "Trigger measurement and read calibrated temperature and humidity.",
    returns: "tuple (temp_c, humidity_rh) as floats.",
    example: "t, h = sensor.read()\nprint('T: %.1f C, H: %.1f%%' % (t, h))",
  },
  {
    id: "bb_devices_sht31_read",
    group: "Devices",
    title: "SHT31.read",
    signature: "(temp, humidity) = sensor.read(repeatability=\"high\", clock_stretch=False)",
    summary: "Trigger and read temperature and relative humidity.",
    args: [
      { name: "repeatability", detail: "'high' (default), 'medium', or 'low'." },
      { name: "clock_stretch", detail: "If True, wait for measurement by stretching clock." },
    ],
    returns: "tuple (temp_c, humidity_rh) as floats.",
    example: "t, h = sensor.read()\nprint('T: %.1f C, H: %.1f%%' % (t, h))",
  },
  {
    id: "bb_devices_bme280_read",
    group: "Devices",
    title: "BME280.read",
    signature: "(temp, press, hum) = sensor.read()",
    summary: "Read BME280 sensor values with full double-precision compensation.",
    returns: "tuple (temp_c, pressure_pa, humidity_rh) as floats.",
    example: "t, p, h = sensor.read()\nprint('T: %.1f C, P: %.1f hPa, H: %.1f%%' % (t, p/100, h))",
  },
  {
    id: "bb_devices_ina219_read",
    group: "Devices",
    title: "INA219.read",
    signature: "(shunt_v, current, power) = sensor.read()",
    summary: "Read shunt voltage, calculated current, and calculated load power.",
    returns: "tuple (shunt_v_volts, current_amps, power_watts) as floats.",
    example: "v, i, p = sensor.read()\nprint('Bus: %.3f V, Current: %.3f A, Power: %.3f W' % (v, i, p))",
  },
  {
    id: "bb_devices_ads1115_read_voltage",
    group: "Devices",
    title: "ADS1115.read_voltage",
    signature: "volts = adc.read_voltage(channel)",
    summary: "Perform a single-ended conversion on the specified channel.",
    args: [
      { name: "channel", detail: "ADC input channel 0..3." },
    ],
    returns: "float voltage in volts.",
    example: "volts = adc.read_voltage(0)\nprint('CH0: %.3f V' % volts)",
  },
  {
    id: "bb_devices_mcp23017_get_pin",
    group: "Devices",
    title: "MCP23017.get_pin",
    signature: "value = gpio.get_pin(pin)",
    summary: "Read the digital input value of one pin.",
    args: [
      { name: "pin", detail: "Pin index 0..15." },
    ],
    returns: "int 0 or 1.",
    example: "state = gpio.get_pin(1)\nprint('Pin 1 state: %d' % state)",
  },
  {
    id: "bb_devices_mcp23017_set_pin",
    group: "Devices",
    title: "MCP23017.set_pin",
    signature: "gpio.set_pin(pin, value)",
    summary: "Set the digital output level of one pin.",
    args: [
      { name: "pin", detail: "Pin index 0..15." },
      { name: "value", detail: "Output value (0, 1, True, False)." },
    ],
    returns: "None",
    example: "gpio.set_pin(0, 1)",
  },
  {
    id: "bb_devices_pcf8574_read",
    group: "Devices",
    title: "PCF8574.read",
    signature: "byte_val = gpio.read()",
    summary: "Read the raw 8-bit input port byte.",
    returns: "int 0..255.",
    example: "val = gpio.read()\nprint('Port value: 0x%02X' % val)",
  },
  {
    id: "bb_devices_pcf8574_write",
    group: "Devices",
    title: "PCF8574.write",
    signature: "gpio.write(value)",
    summary: "Write a raw 8-bit output port byte.",
    args: [
      { name: "value", detail: "Output byte value 0..255." },
    ],
    returns: "None",
    example: "gpio.write(0x55)",
  },
  {
    id: "bb_devices_pcf8574_get_pin",
    group: "Devices",
    title: "PCF8574.get_pin",
    signature: "value = gpio.get_pin(pin)",
    summary: "Read input value of a single pin.",
    args: [
      { name: "pin", detail: "Pin index 0..7." },
    ],
    returns: "int 0 or 1.",
    example: "state = gpio.get_pin(0)",
  },
  {
    id: "bb_devices_pcf8574_set_pin",
    group: "Devices",
    title: "PCF8574.set_pin",
    signature: "gpio.set_pin(pin, value)",
    summary: "Set output level of a single pin.",
    args: [
      { name: "pin", detail: "Pin index 0..7." },
      { name: "value", detail: "Output level (0, 1, True, False)." },
    ],
    returns: "None",
    example: "gpio.set_pin(0, 1)",
  },
  {
    id: "bb_devices_pca9685_set_duty",
    group: "Devices",
    title: "PCA9685.set_duty",
    signature: "pwm.set_duty(channel, duty)",
    summary: "Set the duty cycle of one PWM channel.",
    args: [
      { name: "channel", detail: "Channel index 0..15." },
      { name: "duty", detail: "Float duty cycle from 0.0 to 1.0." },
    ],
    returns: "None",
    example: "pwm.set_duty(0, 0.25)",
  },
  {
    id: "bb_devices_pca9685_set_freq",
    group: "Devices",
    title: "PCA9685.set_freq",
    signature: "pwm.set_freq(freq_hz)",
    summary: "Set the global PWM output clock frequency.",
    args: [
      { name: "freq_hz", detail: "Frequency in Hz, between 24 and 1526." },
    ],
    returns: "None",
    example: "pwm.set_freq(100)",
  },
  {
    id: "bb_devices_tcs34725_read_rgbc",
    group: "Devices",
    title: "TCS34725.read_rgbc",
    signature: "(r, g, b, c) = sensor.read_rgbc()",
    summary: "Read the raw red, green, blue, and clear light channel levels.",
    returns: "tuple (r, g, b, c) of 16-bit raw integers.",
    example: "r, g, b, c = sensor.read_rgbc()\nprint('Clear: %d, Red: %d' % (c, r))",
  },
  {
    id: "bb_devices_mpu6050_read",
    group: "Devices",
    title: "MPU6050.read",
    signature: "data = imu.read()",
    summary: "Read raw 3-axis accelerometer, 3-axis gyroscope, and internal temperature sensor values.",
    returns: "dict: {'accel': (x,y,z), 'gyro': (x,y,z), 'temp': t}",
    example: "data = imu.read()\nprint('Accel X: %.2f g' % data['accel'][0])",
  },
  {
    id: "bb_devices_mcp4725_set_voltage",
    group: "Devices",
    title: "MCP4725.set_voltage",
    signature: "dac.set_voltage(voltage)",
    summary: "Drive DAC output to a specific voltage using vref.",
    args: [
      { name: "voltage", detail: "Float target voltage from 0.0 to vref." },
    ],
    returns: "None",
    example: "dac.set_voltage(2.5)",
  },
  {
    id: "bb_devices_ssd1306_text",
    group: "Devices",
    title: "SSD1306.text",
    signature: "display.text(string, x, y, color=1)",
    summary: "Write text to the internal display frame buffer.",
    args: [
      { name: "string", detail: "The text to draw." },
      { name: "x/y", detail: "Coordinates of top-left pixel." },
      { name: "color", detail: "1 for white, 0 for black; default 1." },
    ],
    returns: "None",
    example: "display.text('Hello', 0, 0)",
  },
  {
    id: "bb_devices_ssd1306_fill",
    group: "Devices",
    title: "SSD1306.fill",
    signature: "display.fill(color)",
    summary: "Fill the entire screen frame buffer with color.",
    args: [
      { name: "color", detail: "1 for white, 0 for black." },
    ],
    returns: "None",
    example: "display.fill(0)",
  },
  {
    id: "bb_devices_ssd1306_show",
    group: "Devices",
    title: "SSD1306.show",
    signature: "display.show()",
    summary: "Write the frame buffer to the physical OLED screen.",
    returns: "None",
    example: "display.show()",
  },
  {
    id: "bb_helpers_channel_sweep",
    group: "Helpers",
    title: "bb_helpers.channel_sweep",
    signature: "results = bb_helpers.channel_sweep(channel, voltages, settle_ms=100, readback=True)",
    summary: "Drive a channel to FUNC_VOUT through an explicit list of voltages, optionally reading back ADC at each step. Restores FUNC_HIGH_IMP on return.",
    args: [
      { name: "channel", detail: "Zero-based channel index, 0..3." },
      { name: "voltages", detail: "Iterable of float voltage values in volts." },
      { name: "settle_ms", detail: "Settle time per step in ms, default 100." },
      { name: "readback", detail: "If True (default) read ADC after each step." },
    ],
    returns: "list of (target_v, readback_v) tuples if readback=True, else list of target_v values.",
    example: "import bb_helpers\n\nfor v, rb in bb_helpers.channel_sweep(0, [0.0, 2.5, 5.0]):\n    print('%.1f -> %.5f' % (v, rb))",
  },
];