export interface ApiDocEntry {
  id: string;
  group: string;
  title: string;
  signature: string;
  summary: string;
  args?: Array<{ name: string; detail: string }>;
  returns?: string;
  raises?: string[];
  example: string;
}

export const functionConstants = [
  ["FUNC_HIGH_IMP", "High impedance input/off state"],
  ["FUNC_VOUT", "Voltage output"],
  ["FUNC_IOUT", "Current output"],
  ["FUNC_VIN", "Voltage input"],
  ["FUNC_IIN_EXT_PWR", "Current input with external loop power"],
  ["FUNC_IIN_LOOP_PWR", "Current input with loop power"],
  ["FUNC_RES_MEAS", "Resistance measurement"],
  ["FUNC_DIN_LOGIC", "Logic digital input"],
  ["FUNC_DIN_LOOP", "Loop digital input"],
  ["FUNC_IOUT_HART", "HART current output"],
  ["FUNC_IIN_EXT_PWR_HART", "HART current input with external loop power"],
  ["FUNC_IIN_LOOP_PWR_HART", "HART current input with loop power"],
  ["HAT_RAIL_3V3_ADJ", "HAT adjustable 3.3 V rail"],
  ["HAT_RAIL_VADJ3", "HAT VADJ3 rail"],
  ["HAT_RAIL_VADJ4", "HAT VADJ4 rail"],
  ["HAT_LED_OFF", "HAT status LED off"],
  ["HAT_LED_RED", "HAT status LED red"],
  ["HAT_LED_GREEN", "HAT status LED green"],
  ["HAT_LED_BLUE", "HAT status LED blue"],
  ["HAT_LED_YELLOW", "HAT status LED yellow"],
  ["HAT_LED_CYAN", "HAT status LED cyan"],
  ["HAT_LED_MAGENTA", "HAT status LED magenta"],
  ["HAT_LED_WHITE", "HAT status LED white"],
] as const;

export const apiDocs: ApiDocEntry[] = [
  {
    id: "sleep",
    group: "Core",
    title: "bugbuster.sleep",
    signature: "bugbuster.sleep(ms)",
    summary: "Cooperative delay that keeps script cancellation responsive.",
    args: [{ name: "ms", detail: "Delay in milliseconds. Must be >= 0." }],
    returns: "None",
    raises: ["ValueError if ms is negative."],
    example: "import bugbuster\n\nbugbuster.sleep(250)\nprint('settled')",
  },
  {
    id: "channel",
    group: "Channels",
    title: "bugbuster.Channel",
    signature: "ch = bugbuster.Channel(channel)",
    summary: "Create a handle for one AD74416H channel.",
    args: [{ name: "channel", detail: "Zero-based channel index, 0..3." }],
    returns: "Channel object.",
    raises: ["ValueError if channel is outside 0..3."],
    example: "import bugbuster\n\nch0 = bugbuster.Channel(0)",
  },
  {
    id: "set_function",
    group: "Channels",
    title: "Channel.set_function",
    signature: "ch.set_function(func)",
    summary: "Set the channel function using one of the bugbuster.FUNC_* constants.",
    args: [{ name: "func", detail: "One of the exported FUNC_* constants." }],
    returns: "None",
    raises: ["ValueError for unknown function codes.", "OSError(EIO) if hardware application fails."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nch.set_function(bugbuster.FUNC_VOUT)",
  },
  {
    id: "set_voltage",
    group: "Channels",
    title: "Channel.set_voltage",
    signature: "ch.set_voltage(voltage, bipolar=False)",
    summary: "Drive a voltage-output channel to the requested voltage.",
    args: [
      { name: "voltage", detail: "Target voltage in volts." },
      { name: "bipolar", detail: "Optional bool, default False." },
    ],
    returns: "None",
    raises: ["OSError(EIO) if the firmware cannot apply the requested DAC value."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nch.set_function(bugbuster.FUNC_VOUT)\nch.set_voltage(2.5)",
  },
  {
    id: "read_voltage",
    group: "Channels",
    title: "Channel.read_voltage",
    signature: "volts = ch.read_voltage()",
    summary: "Read the current measured voltage for the channel.",
    returns: "float voltage in volts.",
    raises: ["OSError(ETIMEDOUT) if ADC readback times out."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nprint(ch.read_voltage())",
  },
  {
    id: "set_do",
    group: "Channels",
    title: "Channel.set_do",
    signature: "ch.set_do(value)",
    summary: "Set digital-output state for a channel configured as an output.",
    args: [{ name: "value", detail: "Truth value. True drives on, False drives off." }],
    returns: "None",
    raises: ["OSError(EBUSY) if the channel is not ready for digital output."],
    example: "import bugbuster\n\nch = bugbuster.Channel(1)\nch.set_do(True)",
  },
  {
    id: "i2c",
    group: "I2C",
    title: "bugbuster.I2C",
    signature: "i2c = bugbuster.I2C(sda_io, scl_io, *, freq=400000, pullups='external', supply=3.3, vlogic=3.3, allow_split_supplies=False)",
    summary: "Route two BugBuster IO terminals to the external I2C engine.",
    args: [
      { name: "sda_io / scl_io", detail: "Logical IO terminal numbers 1..12, not raw GPIOs." },
      { name: "freq", detail: "Bus frequency in Hz, default 400000." },
      { name: "pullups", detail: "'external', 'internal', or 'off'." },
      { name: "supply / vlogic", detail: "Requested target/device rail voltages. supply must be <= 5.0 V." },
    ],
    returns: "I2C object.",
    raises: ["ValueError for invalid IOs, duplicate pins, invalid pullups, unsafe supply, or route setup failure."],
    example: "import bugbuster\n\ni2c = bugbuster.I2C(1, 2, freq=400000, supply=3.3, vlogic=3.3)",
  },
  {
    id: "i2c_scan",
    group: "I2C",
    title: "I2C.scan",
    signature: "devices = i2c.scan(start=0x08, stop=0x77, skip_reserved=True, timeout_ms=50)",
    summary: "Scan for responding 7-bit I2C device addresses.",
    returns: "list[int] of addresses.",
    raises: ["OSError(EIO) if the scan fails."],
    example: "print([hex(a) for a in i2c.scan()])",
  },
  {
    id: "i2c_writeto",
    group: "I2C",
    title: "I2C.writeto",
    signature: "i2c.writeto(addr, buf, timeout_ms=50)",
    summary: "Write bytes to a 7-bit I2C address.",
    args: [
      { name: "addr", detail: "7-bit device address." },
      { name: "buf", detail: "bytes, bytearray, or other readable buffer." },
    ],
    returns: "None",
    raises: ["OSError(EIO) if the transaction fails."],
    example: "i2c.writeto(0x48, bytes([0x00]))",
  },
  {
    id: "i2c_readfrom",
    group: "I2C",
    title: "I2C.readfrom",
    signature: "data = i2c.readfrom(addr, n, timeout_ms=50)",
    summary: "Read bytes from a 7-bit I2C address.",
    args: [{ name: "n", detail: "Number of bytes to read, 1..512." }],
    returns: "bytes",
    raises: ["ValueError if n is outside 1..512.", "OSError(ETIMEDOUT) if the transaction times out."],
    example: "raw = i2c.readfrom(0x48, 2)",
  },
  {
    id: "i2c_write_read",
    group: "I2C",
    title: "I2C.writeto_then_readfrom",
    signature: "data = i2c.writeto_then_readfrom(addr, wr_buf, rd_n, timeout_ms=50)",
    summary: "Perform a write-then-read I2C transaction.",
    args: [{ name: "rd_n", detail: "Number of response bytes, 1..512." }],
    returns: "bytes",
    raises: ["ValueError if rd_n is outside 1..512.", "OSError(EIO) if the transaction fails."],
    example: "chip_id = i2c.writeto_then_readfrom(0x76, bytes([0xD0]), 1)",
  },
  {
    id: "spi",
    group: "SPI",
    title: "bugbuster.SPI",
    signature: "spi = bugbuster.SPI(sck_io, *, mosi_io=None, miso_io=None, cs_io=None, freq=1000000, mode=0, supply=3.3, vlogic=3.3, allow_split_supplies=False)",
    summary: "Route BugBuster IO terminals to the external SPI engine.",
    args: [
      { name: "sck_io", detail: "Required logical IO terminal 1..12." },
      { name: "mosi_io / miso_io / cs_io", detail: "Optional logical IO terminals 1..12 or None." },
      { name: "mode", detail: "SPI mode 0..3." },
    ],
    returns: "SPI object.",
    raises: ["ValueError for invalid IOs, mode, unsafe supply, or route setup failure."],
    example: "import bugbuster\n\nspi = bugbuster.SPI(1, mosi_io=2, miso_io=3, cs_io=4, freq=1000000)",
  },
  {
    id: "spi_transfer",
    group: "SPI",
    title: "SPI.transfer",
    signature: "rx = spi.transfer(buf)",
    summary: "Run a full-duplex SPI transfer. RX length matches TX length.",
    args: [{ name: "buf", detail: "Readable buffer, 1..512 bytes." }],
    returns: "bytes",
    raises: ["ValueError if buffer is empty or larger than 512 bytes.", "OSError(EIO) if the transfer fails."],
    example: "jedec = spi.transfer(bytes([0x9F, 0x00, 0x00, 0x00]))",
  },
  {
    id: "http_get",
    group: "Network",
    title: "bugbuster.http_get",
    signature: "r = bugbuster.http_get(url, *, headers=None, timeout_ms=10000)",
    summary: "Issue an HTTP/HTTPS GET from the device.",
    returns: "Response attrtuple with r.status and r.body bytes.",
    raises: ["ValueError for invalid timeout.", "OSError(ECONNABORTED) on transport failure.", "KeyboardInterrupt if stopped after request returns."],
    example: "r = bugbuster.http_get('https://example.com')\nprint(r.status, r.body[:32])",
  },
  {
    id: "http_post",
    group: "Network",
    title: "bugbuster.http_post",
    signature: "r = bugbuster.http_post(url, body=b'', *, headers=None, timeout_ms=10000)",
    summary: "Issue an HTTP/HTTPS POST from the device.",
    returns: "Response attrtuple with r.status and r.body bytes.",
    raises: ["ValueError for invalid timeout.", "OSError(ECONNABORTED) on transport failure.", "KeyboardInterrupt if stopped after request returns."],
    example: "r = bugbuster.http_post('https://example.com', b'payload')\nprint(r.status)",
  },
  {
    id: "mqtt_publish",
    group: "Network",
    title: "bugbuster.mqtt_publish",
    signature: "bugbuster.mqtt_publish(topic, payload, host, *, port=1883, username=None, password=None)",
    summary: "Publish a single MQTT message from the device.",
    args: [
      { name: "topic", detail: "MQTT topic string." },
      { name: "payload", detail: "Readable bytes-like payload." },
      { name: "host", detail: "Broker hostname or IP." },
    ],
    returns: "None",
    raises: ["ValueError if port is outside 1..65535.", "OSError(ECONNABORTED) if publishing fails."],
    example: "bugbuster.mqtt_publish('bench/status', b'ok', '192.168.1.10')",
  },
  {
    id: "hat_status",
    group: "HAT",
    title: "bugbuster.hat_status",
    signature: "status = bugbuster.hat_status()",
    summary: "Return the ESP32 snapshot of HAT presence, UART health, firmware version, pins, SWD state, and v2 telemetry.",
    returns: "dict with detected, connected, fw_major/fw_minor, pin_config, degraded, and related status fields.",
    raises: ["OSError(EIO) if the HAT state is unavailable."],
    example: "import bugbuster\n\nstatus = bugbuster.hat_status()\nprint(status['detected'], status['connected'])",
  },
  {
    id: "hat_caps",
    group: "HAT",
    title: "bugbuster.hat_caps",
    signature: "caps = bugbuster.hat_caps()",
    summary: "Query HAT v2 capability metadata from the RP2040.",
    returns: "dict with hw_revision, flags, rail_count, led_count, shifted_io_count, la_routes, fw_major, fw_minor, hvpak_present.",
    raises: ["OSError(EIO) when no HAT is connected or the UART command fails."],
    example: "caps = bugbuster.hat_caps()\nprint(caps['rail_count'], caps['led_count'])",
  },
  {
    id: "hat_rails",
    group: "HAT",
    title: "bugbuster.hat_rails",
    signature: "rails = bugbuster.hat_rails()",
    summary: "Read HAT rail enable state, measured voltage, current, and fault status.",
    returns: "list[dict] with rail_id, enabled, voltage_mv, current_ma, status.",
    raises: ["OSError(EIO) when no HAT is connected or the rail status command fails."],
    example: "for rail in bugbuster.hat_rails():\n    print(rail['rail_id'], rail['voltage_mv'], rail['enabled'])",
  },
  {
    id: "hat_set_rail_enable",
    group: "HAT",
    title: "bugbuster.hat_set_rail_enable",
    signature: "bugbuster.hat_set_rail_enable(rail_id, enable)",
    summary: "Enable or disable a HAT v2 rail.",
    args: [{ name: "rail_id", detail: "0=3V3_ADJ, 1=VADJ3, 2=VADJ4." }, { name: "enable", detail: "Boolean output enable." }],
    returns: "None",
    raises: ["ValueError for invalid rail_id.", "OSError(EIO) if the HAT rejects the command."],
    example: "bugbuster.hat_set_rail_enable(bugbuster.HAT_RAIL_VADJ3, True)",
  },
  {
    id: "hat_set_rail_voltage",
    group: "HAT",
    title: "bugbuster.hat_set_rail_voltage",
    signature: "bugbuster.hat_set_rail_voltage(rail_id, voltage_mv)",
    summary: "Set a HAT adjustable rail target voltage in millivolts.",
    args: [{ name: "voltage_mv", detail: "Requested target in mV. Firmware/HAT enforce rail-specific safe ranges." }],
    returns: "None",
    raises: ["ValueError for invalid rail_id or voltage range.", "OSError(EIO) if the HAT rejects the command."],
    example: "bugbuster.hat_set_rail_voltage(bugbuster.HAT_RAIL_VADJ4, 5000)",
  },
  {
    id: "hat_led",
    group: "HAT",
    title: "bugbuster.hat_led",
    signature: "bugbuster.hat_led(led_id, color_code)",
    summary: "Set one of the eight HAT status LEDs.",
    args: [{ name: "led_id", detail: "1..8." }, { name: "color_code", detail: "Use HAT_LED_* constants or 0..255 raw code." }],
    returns: "None",
    raises: ["ValueError for invalid LED or color.", "OSError(EIO) if the command fails."],
    example: "bugbuster.hat_led(1, bugbuster.HAT_LED_GREEN)",
  },
  {
    id: "hat_io_bank",
    group: "HAT",
    title: "bugbuster.hat_io_bank",
    signature: "bugbuster.hat_io_bank(dirs, *, ups=0, dns=0, vals=0)",
    summary: "Configure the HAT shifted IO bank directions, pulls, and optional output values as bit masks.",
    args: [{ name: "dirs", detail: "Direction mask, 1=output." }, { name: "ups / dns / vals", detail: "Pull-up, pull-down, and output value masks." }],
    returns: "None",
    raises: ["ValueError if masks are outside 0..255.", "OSError(EIO) if the command fails."],
    example: "bugbuster.hat_io_bank(0b00001111, ups=0, dns=0, vals=0b00000101)",
  },
  {
    id: "hat_level_shift",
    group: "HAT",
    title: "bugbuster.hat_level_shift",
    signature: "state = bugbuster.hat_level_shift(oe, dir)",
    summary: "Override HAT level-shifter output-enable and direction pins.",
    returns: "dict with oe and dir fields reflecting the applied state.",
    raises: ["OSError(EIO) if the command fails."],
    example: "print(bugbuster.hat_level_shift(True, True))",
  },
  {
    id: "hat_calibrate_status",
    group: "HAT Calibration",
    title: "bugbuster.hat_calibrate_status",
    signature: "status = bugbuster.hat_calibrate_status()",
    summary: "Read HAT rail calibration sweep state and validation telemetry.",
    returns: "dict with state, progress, rail_id, last_error, stage, point, code, measured_mv, min/max/gap/error telemetry, validation_flags.",
    raises: ["OSError(EIO) if the command fails."],
    example: "print(bugbuster.hat_calibrate_status())",
  },
  {
    id: "hat_calibrate_start",
    group: "HAT Calibration",
    title: "bugbuster.hat_calibrate_start",
    signature: "state = bugbuster.hat_calibrate_start(rail_id)",
    summary: "Start HAT rail auto-calibration for VADJ3 or VADJ4.",
    returns: "Initial calibration state code.",
    raises: ["ValueError for invalid rail_id.", "OSError(EIO) if calibration cannot start."],
    example: "bugbuster.hat_calibrate_start(bugbuster.HAT_RAIL_VADJ3)",
  },
  {
    id: "hat_calibrate_import",
    group: "HAT Calibration",
    title: "bugbuster.hat_calibrate_import",
    signature: "bugbuster.hat_calibrate_import(rail_id, points)",
    summary: "Import 2..6 calibration points into the HAT. Each point is a `(dac_code, measured_v)` pair.",
    returns: "None",
    raises: ["ValueError for invalid rail or point list.", "OSError(EIO) if the HAT rejects the import."],
    example: "bugbuster.hat_calibrate_import(1, [(-8, 3.42), (0, 3.30), (8, 3.18)])",
  },
  {
    id: "hat_setup_swd",
    group: "HAT",
    title: "bugbuster.hat_setup_swd",
    signature: "bugbuster.hat_setup_swd(target_voltage_mv=3300, *, connector=0)",
    summary: "Run the ESP32 HAT SWD setup sequence for the dedicated CMSIS-DAP connector.",
    returns: "None",
    raises: ["ValueError for invalid voltage or connector.", "OSError(EIO) if setup fails."],
    example: "bugbuster.hat_setup_swd(3300, connector=0)",
  },
];
