export interface ApiDocEntry {
  id: string;
  group: string;
  title: string;
  signature: string;
  summary: string;
  args?: Array<{ name: string; detail: string }>;
  returns?: string;
  raises?: string[];
  example: string;
}

export const functionConstants = [
  ["FUNC_HIGH_IMP", "High impedance input/off state"],
  ["FUNC_VOUT", "Voltage output"],
  ["FUNC_IOUT", "Current output"],
  ["FUNC_VIN", "Voltage input"],
  ["FUNC_IIN_EXT_PWR", "Current input with external loop power"],
  ["FUNC_IIN_LOOP_PWR", "Current input with loop power"],
  ["FUNC_RES_MEAS", "Resistance measurement"],
  ["FUNC_DIN_LOGIC", "Logic digital input"],
  ["FUNC_DIN_LOOP", "Loop digital input"],
  ["FUNC_IOUT_HART", "HART current output"],
  ["FUNC_IIN_EXT_PWR_HART", "HART current input with external loop power"],
  ["FUNC_IIN_LOOP_PWR_HART", "HART current input with loop power"],
] as const;

export const apiDocs: ApiDocEntry[] = [
  {
    id: "sleep",
    group: "Core",
    title: "bugbuster.sleep",
    signature: "bugbuster.sleep(ms)",
    summary: "Cooperative delay that keeps script cancellation responsive.",
    args: [{ name: "ms", detail: "Delay in milliseconds. Must be >= 0." }],
    returns: "None",
    raises: ["ValueError if ms is negative."],
    example: "import bugbuster\n\nbugbuster.sleep(250)\nprint('settled')",
  },
  {
    id: "channel",
    group: "Channels",
    title: "bugbuster.Channel",
    signature: "ch = bugbuster.Channel(channel)",
    summary: "Create a handle for one AD74416H channel.",
    args: [{ name: "channel", detail: "Zero-based channel index, 0..3." }],
    returns: "Channel object.",
    raises: ["ValueError if channel is outside 0..3."],
    example: "import bugbuster\n\nch0 = bugbuster.Channel(0)",
  },
  {
    id: "set_function",
    group: "Channels",
    title: "Channel.set_function",
    signature: "ch.set_function(func)",
    summary: "Set the channel function using one of the bugbuster.FUNC_* constants.",
    args: [{ name: "func", detail: "One of the exported FUNC_* constants." }],
    returns: "None",
    raises: ["ValueError for unknown function codes.", "OSError(EIO) if hardware application fails."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nch.set_function(bugbuster.FUNC_VOUT)",
  },
  {
    id: "set_voltage",
    group: "Channels",
    title: "Channel.set_voltage",
    signature: "ch.set_voltage(voltage, bipolar=False)",
    summary: "Drive a voltage-output channel to the requested voltage.",
    args: [
      { name: "voltage", detail: "Target voltage in volts." },
      { name: "bipolar", detail: "Optional bool, default False." },
    ],
    returns: "None",
    raises: ["OSError(EIO) if the firmware cannot apply the requested DAC value."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nch.set_function(bugbuster.FUNC_VOUT)\nch.set_voltage(2.5)",
  },
  {
    id: "read_voltage",
    group: "Channels",
    title: "Channel.read_voltage",
    signature: "volts = ch.read_voltage()",
    summary: "Read the current measured voltage for the channel.",
    returns: "float voltage in volts.",
    raises: ["OSError(ETIMEDOUT) if ADC readback times out."],
    example: "import bugbuster\n\nch = bugbuster.Channel(0)\nprint(ch.read_voltage())",
  },
  {
    id: "set_do",
    group: "Channels",
    title: "Channel.set_do",
    signature: "ch.set_do(value)",
    summary: "Set digital-output state for a channel configured as an output.",
    args: [{ name: "value", detail: "Truth value. True drives on, False drives off." }],
    returns: "None",
    raises: ["OSError(EBUSY) if the channel is not ready for digital output."],
    example: "import bugbuster\n\nch = bugbuster.Channel(1)\nch.set_do(True)",
  },
  {
    id: "i2c",
    group: "I2C",
    title: "bugbuster.I2C",
    signature: "i2c = bugbuster.I2C(sda_io, scl_io, *, freq=400000, pullups='external', supply=3.3, vlogic=3.3, allow_split_supplies=False)",
    summary: "Route two BugBuster IO terminals to the external I2C engine.",
    args: [
      { name: "sda_io / scl_io", detail: "Logical IO terminal numbers 1..12, not raw GPIOs." },
      { name: "freq", detail: "Bus frequency in Hz, default 400000." },
      { name: "pullups", detail: "'external', 'internal', or 'off'." },
      { name: "supply / vlogic", detail: "Requested target/device rail voltages. supply must be <= 5.0 V." },
    ],
    returns: "I2C object.",
    raises: ["ValueError for invalid IOs, duplicate pins, invalid pullups, unsafe supply, or route setup failure."],
    example: "import bugbuster\n\ni2c = bugbuster.I2C(1, 2, freq=400000, supply=3.3, vlogic=3.3)",
  },
  {
    id: "i2c_scan",
    group: "I2C",
    title: "I2C.scan",
    signature: "devices = i2c.scan(start=0x08, stop=0x77, skip_reserved=True, timeout_ms=50)",
    summary: "Scan for responding 7-bit I2C device addresses.",
    returns: "list[int] of addresses.",
    raises: ["OSError(EIO) if the scan fails."],
    example: "print([hex(a) for a in i2c.scan()])",
  },
  {
    id: "i2c_writeto",
    group: "I2C",
    title: "I2C.writeto",
    signature: "i2c.writeto(addr, buf, timeout_ms=50)",
    summary: "Write bytes to a 7-bit I2C address.",
    args: [
      { name: "addr", detail: "7-bit device address." },
      { name: "buf", detail: "bytes, bytearray, or other readable buffer." },
    ],
    returns: "None",
    raises: ["OSError(EIO) if the transaction fails."],
    example: "i2c.writeto(0x48, bytes([0x00]))",
  },
  {
    id: "i2c_readfrom",
    group: "I2C",
    title: "I2C.readfrom",
    signature: "data = i2c.readfrom(addr, n, timeout_ms=50)",
    summary: "Read bytes from a 7-bit I2C address.",
    args: [{ name: "n", detail: "Number of bytes to read, 1..512." }],
    returns: "bytes",
    raises: ["ValueError if n is outside 1..512.", "OSError(ETIMEDOUT) if the transaction times out."],
    example: "raw = i2c.readfrom(0x48, 2)",
  },
  {
    id: "i2c_write_read",
    group: "I2C",
    title: "I2C.writeto_then_readfrom",
    signature: "data = i2c.writeto_then_readfrom(addr, wr_buf, rd_n, timeout_ms=50)",
    summary: "Perform a write-then-read I2C transaction.",
    args: [{ name: "rd_n", detail: "Number of response bytes, 1..512." }],
    returns: "bytes",
    raises: ["ValueError if rd_n is outside 1..512.", "OSError(EIO) if the transaction fails."],
    example: "chip_id = i2c.writeto_then_readfrom(0x76, bytes([0xD0]), 1)",
  },
  {
    id: "spi",
    group: "SPI",
    title: "bugbuster.SPI",
    signature: "spi = bugbuster.SPI(sck_io, *, mosi_io=None, miso_io=None, cs_io=None, freq=1000000, mode=0, supply=3.3, vlogic=3.3, allow_split_supplies=False)",
    summary: "Route BugBuster IO terminals to the external SPI engine.",
    args: [
      { name: "sck_io", detail: "Required logical IO terminal 1..12." },
      { name: "mosi_io / miso_io / cs_io", detail: "Optional logical IO terminals 1..12 or None." },
      { name: "mode", detail: "SPI mode 0..3." },
    ],
    returns: "SPI object.",
    raises: ["ValueError for invalid IOs, mode, unsafe supply, or route setup failure."],
    example: "import bugbuster\n\nspi = bugbuster.SPI(1, mosi_io=2, miso_io=3, cs_io=4, freq=1000000)",
  },
  {
    id: "spi_transfer",
    group: "SPI",
    title: "SPI.transfer",
    signature: "rx = spi.transfer(buf)",
    summary: "Run a full-duplex SPI transfer. RX length matches TX length.",
    args: [{ name: "buf", detail: "Readable buffer, 1..512 bytes." }],
    returns: "bytes",
    raises: ["ValueError if buffer is empty or larger than 512 bytes.", "OSError(EIO) if the transfer fails."],
    example: "jedec = spi.transfer(bytes([0x9F, 0x00, 0x00, 0x00]))",
  },
  {
    id: "http_get",
    group: "Network",
    title: "bugbuster.http_get",
    signature: "r = bugbuster.http_get(url, *, headers=None, timeout_ms=10000)",
    summary: "Issue an HTTP/HTTPS GET from the device.",
    returns: "Response attrtuple with r.status and r.body bytes.",
    raises: ["ValueError for invalid timeout.", "OSError(ECONNABORTED) on transport failure.", "KeyboardInterrupt if stopped after request returns."],
    example: "r = bugbuster.http_get('https://example.com')\nprint(r.status, r.body[:32])",
  },
  {
    id: "http_post",
    group: "Network",
    title: "bugbuster.http_post",
    signature: "r = bugbuster.http_post(url, body=b'', *, headers=None, timeout_ms=10000)",
    summary: "Issue an HTTP/HTTPS POST from the device.",
    returns: "Response attrtuple with r.status and r.body bytes.",
    raises: ["ValueError for invalid timeout.", "OSError(ECONNABORTED) on transport failure.", "KeyboardInterrupt if stopped after request returns."],
    example: "r = bugbuster.http_post('https://example.com', b'payload')\nprint(r.status)",
  },
  {
    id: "mqtt_publish",
    group: "Network",
    title: "bugbuster.mqtt_publish",
    signature: "bugbuster.mqtt_publish(topic, payload, host, *, port=1883, username=None, password=None)",
    summary: "Publish a single MQTT message from the device.",
    args: [
      { name: "topic", detail: "MQTT topic string." },
      { name: "payload", detail: "Readable bytes-like payload." },
      { name: "host", detail: "Broker hostname or IP." },
    ],
    returns: "None",
    raises: ["ValueError if port is outside 1..65535.", "OSError(ECONNABORTED) if publishing fails."],
    example: "bugbuster.mqtt_publish('bench/status', b'ok', '192.168.1.10')",
  },
];
