import { CompletionSource, snippetCompletion } from "@codemirror/autocomplete";

export const bugbusterCompletions: CompletionSource = (context) => {
  // Match the word being typed, including dots for module access
  let word = context.matchBefore(/[\w.]*/);
  if (!word || (word.from === word.to && !context.explicit)) return null;

  return {
    from: word.from,
    options: [
      // Modules
      { label: "bugbuster", type: "namespace" },
      { label: "bb_helpers", type: "namespace" },
      { label: "bb_devices", type: "namespace" },
      { label: "bb_logging", type: "namespace" },

      // bugbuster functions
      snippetCompletion("bugbuster.sleep(${ms})", { label: "bugbuster.sleep", detail: "cooperative sleep", type: "function" }),
      snippetCompletion("bugbuster.Channel(${id})", { label: "bugbuster.Channel", detail: "analog channel (0-3)", type: "class" }),
      snippetCompletion("bugbuster.I2C(sda_io=${sda}, scl_io=${scl}, freq=${400000})", { label: "bugbuster.I2C", detail: "I2C bus setup", type: "class" }),
      snippetCompletion("i2c.close()", { label: "I2C.close", detail: "release shared I2C controller", type: "method" }),
      snippetCompletion("bugbuster.SPI(sck_io=${sck}, mosi_io=${mosi}, miso_io=${miso}, cs_io=${cs})", { label: "bugbuster.SPI", detail: "SPI bus setup", type: "class" }),
      snippetCompletion("spi.close()", { label: "SPI.close", detail: "release shared SPI controller", type: "method" }),
      snippetCompletion("bugbuster.http_get('${url}')", { label: "bugbuster.http_get", type: "function" }),
      snippetCompletion("bugbuster.http_post('${url}', body=${body})", { label: "bugbuster.http_post", type: "function" }),
      snippetCompletion("bugbuster.mqtt_publish(topic='${topic}', payload=${payload}, host='${host}')", { label: "bugbuster.mqtt_publish", type: "function" }),
      snippetCompletion("bugbuster.hat_status()", { label: "bugbuster.hat_status", detail: "HAT presence and health", type: "function" }),
      snippetCompletion("bugbuster.hat_caps()", { label: "bugbuster.hat_caps", detail: "HAT v2 capabilities", type: "function" }),
      snippetCompletion("bugbuster.hat_rails()", { label: "bugbuster.hat_rails", detail: "HAT rail status", type: "function" }),
      snippetCompletion("bugbuster.hat_set_rail_enable(${rail_id}, ${enable})", { label: "bugbuster.hat_set_rail_enable", type: "function" }),
      snippetCompletion("bugbuster.hat_set_rail_voltage(${rail_id}, ${voltage_mv})", { label: "bugbuster.hat_set_rail_voltage", type: "function" }),
      snippetCompletion("bugbuster.hat_led(${led_id}, ${color_code})", { label: "bugbuster.hat_led", type: "function" }),
      snippetCompletion("bugbuster.hat_io_bank(${dirs}, ups=${0}, dns=${0}, vals=${0})", { label: "bugbuster.hat_io_bank", type: "function" }),
      snippetCompletion("bugbuster.hat_level_shift(${oe}, ${dir})", { label: "bugbuster.hat_level_shift", type: "function" }),
      snippetCompletion("bugbuster.hat_calibrate_status()", { label: "bugbuster.hat_calibrate_status", type: "function" }),
      snippetCompletion("bugbuster.hat_calibrate_start(${rail_id})", { label: "bugbuster.hat_calibrate_start", type: "function" }),
      snippetCompletion("bugbuster.hat_calibrate_import(${rail_id}, ${points})", { label: "bugbuster.hat_calibrate_import", type: "function" }),
      snippetCompletion("bugbuster.hat_setup_swd(${3300}, connector=${0})", { label: "bugbuster.hat_setup_swd", type: "function" }),

      // Constants
      { label: "bugbuster.FUNC_HIGH_IMP", type: "constant" },
      { label: "bugbuster.FUNC_VOUT", type: "constant" },
      { label: "bugbuster.FUNC_IOUT", type: "constant" },
      { label: "bugbuster.FUNC_VIN", type: "constant" },
      { label: "bugbuster.FUNC_IIN_EXT_PWR", type: "constant" },
      { label: "bugbuster.FUNC_IIN_LOOP_PWR", type: "constant" },
      { label: "bugbuster.FUNC_RES_MEAS", type: "constant" },
      { label: "bugbuster.FUNC_DIN_LOGIC", type: "constant" },
      { label: "bugbuster.FUNC_DIN_LOOP", type: "constant" },
      { label: "bugbuster.FUNC_IOUT_HART", type: "constant" },
      { label: "bugbuster.FUNC_IIN_EXT_PWR_HART", type: "constant" },
      { label: "bugbuster.FUNC_IIN_LOOP_PWR_HART", type: "constant" },
      { label: "bugbuster.HAT_RAIL_3V3_ADJ", type: "constant" },
      { label: "bugbuster.HAT_RAIL_VADJ3", type: "constant" },
      { label: "bugbuster.HAT_RAIL_VADJ4", type: "constant" },
      { label: "bugbuster.HAT_LED_OFF", type: "constant" },
      { label: "bugbuster.HAT_LED_RED", type: "constant" },
      { label: "bugbuster.HAT_LED_GREEN", type: "constant" },
      { label: "bugbuster.HAT_LED_BLUE", type: "constant" },
      { label: "bugbuster.HAT_LED_YELLOW", type: "constant" },
      { label: "bugbuster.HAT_LED_CYAN", type: "constant" },
      { label: "bugbuster.HAT_LED_MAGENTA", type: "constant" },
      { label: "bugbuster.HAT_LED_WHITE", type: "constant" },

      // Methods (generic, will match after 'ch.' etc)
      snippetCompletion("set_function(${func})", { label: "set_function", type: "method" }),
      snippetCompletion("set_voltage(${v})", { label: "set_voltage", type: "method" }),
      snippetCompletion("read_voltage()", { label: "read_voltage", type: "method" }),
      snippetCompletion("set_do(${value})", { label: "set_do", type: "method" }),
      snippetCompletion("scan()", { label: "scan", type: "method" }),
      snippetCompletion("writeto(${addr}, ${data})", { label: "writeto", type: "method" }),
      snippetCompletion("readfrom(${addr}, ${n})", { label: "readfrom", type: "method" }),
      snippetCompletion("writeto_then_readfrom(${addr}, ${wr_buf}, ${rd_n})", { label: "writeto_then_readfrom", type: "method" }),
      snippetCompletion("transfer(${data})", { label: "transfer", type: "method" }),

      // bb_helpers
      snippetCompletion("bb_helpers.settle(${ms})", { label: "bb_helpers.settle", type: "function" }),
      snippetCompletion("bb_helpers.dac_ramp(channel=${ch}, lo=${0.0}, hi=${5.0}, step=${1.0})", { label: "bb_helpers.dac_ramp", type: "function" }),

      // bb_logging
      snippetCompletion("bb_logging.info('${msg}')", { label: "bb_logging.info", type: "function" }),
      snippetCompletion("bb_logging.warn('${msg}')", { label: "bb_logging.warn", type: "function" }),
      snippetCompletion("bb_logging.error('${msg}')", { label: "bb_logging.error", type: "function" }),

      // bb_devices
      snippetCompletion("bb_devices.TMP102(${i2c}, addr=${0x48})", { label: "bb_devices.TMP102", type: "class" }),
      snippetCompletion("bb_devices.BMP280(${i2c}, addr=${0x76})", { label: "bb_devices.BMP280", type: "class" }),
      snippetCompletion("bb_devices.MCP3008(${spi})", { label: "bb_devices.MCP3008", type: "class" }),
      snippetCompletion("bb_devices.DS18B20(${pin})", { label: "bb_devices.DS18B20", type: "class" }),
      snippetCompletion("bb_devices.DS3231(${i2c}, addr=${0x68})", { label: "bb_devices.DS3231", type: "class" }),
      snippetCompletion("bb_devices.BH1750(${i2c}, addr=${0x23})", { label: "bb_devices.BH1750", type: "class" }),
      snippetCompletion("bb_devices.AHT20(${i2c}, addr=${0x38})", { label: "bb_devices.AHT20", type: "class" }),
      snippetCompletion("bb_devices.SHT31(${i2c}, addr=${0x44})", { label: "bb_devices.SHT31", type: "class" }),
      snippetCompletion("bb_devices.BME280(${i2c}, addr=${0x76})", { label: "bb_devices.BME280", type: "class" }),
      snippetCompletion("bb_devices.INA219(${i2c}, addr=${0x40})", { label: "bb_devices.INA219", type: "class" }),
      snippetCompletion("bb_devices.ADS1115(${i2c}, addr=${0x48})", { label: "bb_devices.ADS1115", type: "class" }),
      snippetCompletion("bb_devices.MCP23017(${i2c}, addr=${0x20})", { label: "bb_devices.MCP23017", type: "class" }),
      snippetCompletion("bb_devices.PCF8574(${i2c}, addr=${0x20})", { label: "bb_devices.PCF8574", type: "class" }),
      snippetCompletion("bb_devices.PCA9685(${i2c}, addr=${0x40})", { label: "bb_devices.PCA9685", type: "class" }),
      snippetCompletion("bb_devices.TCS34725(${i2c}, addr=${0x29})", { label: "bb_devices.TCS34725", type: "class" }),
      snippetCompletion("bb_devices.MPU6050(${i2c}, addr=${0x68})", { label: "bb_devices.MPU6050", type: "class" }),
      snippetCompletion("bb_devices.MCP4725(${i2c}, addr=${0x60})", { label: "bb_devices.MCP4725", type: "class" }),
      snippetCompletion("bb_devices.SSD1306(${width}, ${height}, ${i2c})", { label: "bb_devices.SSD1306", type: "class" }),
      snippetCompletion("pin_mode(${pin}, output=true, pullup=false)", { label: "MCP23017.pin_mode", type: "method" }),
      snippetCompletion("set_dir(${pin}, output=true)", { label: "MCP23017.set_dir", type: "method" }),
      snippetCompletion("set_pullup(${pin}, enable=true)", { label: "MCP23017.set_pullup", type: "method" }),
      snippetCompletion("read_celsius()", { label: "read_celsius", type: "method" }),
      snippetCompletion("read_all()", { label: "read_all", type: "method" }),
      snippetCompletion("read_datetime()", { label: "read_datetime", type: "method" }),
      snippetCompletion("set_datetime(${year}, ${month}, ${day}, ${weekday}, ${hour}, ${minute}, ${second})", { label: "set_datetime", type: "method" }),
      snippetCompletion("temperature_c()", { label: "temperature_c", type: "method" }),
      snippetCompletion("read_lux()", { label: "read_lux", type: "method" }),
      snippetCompletion("read_voltage(${channel})", { label: "read_voltage", type: "method" }),
      snippetCompletion("get_pin(${pin})", { label: "get_pin", type: "method" }),
      snippetCompletion("set_pin(${pin}, ${value})", { label: "set_pin", type: "method" }),
      snippetCompletion("set_duty(${channel}, ${duty})", { label: "set_duty", type: "method" }),
      snippetCompletion("set_freq(${freq})", { label: "set_freq", type: "method" }),
      snippetCompletion("read_rgbc()", { label: "read_rgbc", type: "method" }),
      snippetCompletion("fill(${color})", { label: "fill", type: "method" }),
      snippetCompletion("text('${text}', ${x}, ${y})", { label: "text", type: "method" }),
      snippetCompletion("show()", { label: "show", type: "method" }),
    ],
    validFor: /^[\w.]*$/,
  };
};
