// GENERATED by python/tools/stubs_to_json.py from python/firmware_modules/stubs/*.pyi -- do not edit.
// Regenerate: python python/tools/stubs_to_json.py
export interface GeneratedCompletion {
  label: string;
  snippet: string;
  type: "function" | "class" | "method" | "constant" | "namespace";
  detail: string;
  info: string;
}

export const generatedCompletions: GeneratedCompletion[] = [
 {
  "label": "bugbuster",
  "snippet": "bugbuster",
  "type": "namespace",
  "detail": "BugBuster board control from on-device MicroPython scripts.",
  "info": "BugBuster board control from on-device MicroPython scripts."
 },
 {
  "label": "bugbuster.sleep",
  "snippet": "bugbuster.sleep(${ms})",
  "type": "function",
  "detail": "Pause the script for ``ms`` milliseconds; a Stop request interrupts it.",
  "info": "Pause the script for ``ms`` milliseconds; a Stop request interrupts it.\nms: Delay in milliseconds, 0 or more."
 },
 {
  "label": "bugbuster.log",
  "snippet": "bugbuster.log(${level}, ${msg})",
  "type": "function",
  "detail": "Write a line to the script log (source ``mpy``) and the console.",
  "info": "Write a line to the script log (source ``mpy``) and the console.\nlevel: One character: 'E' error, 'W' warning, 'I' info, 'D' debug.\nmsg: Message text."
 },
 {
  "label": "bugbuster.ticks_ms",
  "snippet": "bugbuster.ticks_ms()",
  "type": "function",
  "detail": "Return the millisecond tick counter (time since boot).",
  "info": "Return the millisecond tick counter (time since boot).\nreturns: Milliseconds since boot."
 },
 {
  "label": "bugbuster.vadj_pd_warning",
  "snippet": "bugbuster.vadj_pd_warning(${rail}, ${voltage})",
  "type": "function",
  "detail": "Check whether the USB-C input can supply a VADJ rail voltage.",
  "info": "Check whether the USB-C input can supply a VADJ rail voltage.\nrail: VADJ rail, 1 or 2.\nvoltage: Requested rail voltage in volts.\nreturns: A warning sentence explaining why the voltage is not available, or ``None`` when the request is fine."
 },
 {
  "label": "bugbuster.rail_power_up",
  "snippet": "bugbuster.rail_power_up(${rail}, ${volts}, ${efuse_mask})",
  "type": "function",
  "detail": "Bring a VADJ rail up to ``volts`` and arm its e-fuses.",
  "info": "Bring a VADJ rail up to ``volts`` and arm its e-fuses.\nrail: VADJ rail, 1 (IO1-IO6) or 2 (IO7-IO12).\nvolts: Target voltage, 3-12 V. The rail quantises to about 0.1 V steps.\nefuse_mask: E-fuses to arm, 1-3 (bit 0 = first e-fuse of the rail: EFUSE1 for rail 1, EFUSE3 for rail 2; bit 1 = second: EFUSE2 / EFUSE4; 3 = both).\nreturns: A dict reporting the result."
 },
 {
  "label": "bugbuster.efuse_set",
  "snippet": "bugbuster.efuse_set(${efuse}, ${on})",
  "type": "function",
  "detail": "Switch one e-fuse on or off.",
  "info": "Switch one e-fuse on or off.\nefuse: E-fuse number, 1-4.\non: True to supply the terminals, False to cut power."
 },
 {
  "label": "bugbuster.http_get",
  "snippet": "bugbuster.http_get(${url})",
  "type": "function",
  "detail": "HTTP or HTTPS GET.",
  "info": "HTTP or HTTPS GET.\nurl: Full URL, ``http://`` or ``https://``.\nheaders: Extra request headers as a dict of str to str, at most 16.\ntimeout_ms: Timeout in milliseconds, greater than 0. Default 10000.\nreturns: A :class:`Response` ``(status, body)``."
 },
 {
  "label": "bugbuster.http_post",
  "snippet": "bugbuster.http_post(${url})",
  "type": "function",
  "detail": "HTTP or HTTPS POST.",
  "info": "HTTP or HTTPS POST.\nurl: Full URL, ``http://`` or ``https://``.\nbody: Request body as bytes or bytearray (``str`` must be encoded first: ``\"x\".encode()``); None sends an empty body.\nheaders: Extra request headers as a dict of str to str, at most 16.\ntimeout_ms: Timeout in milliseconds, greater than 0. Default 10000.\nreturns: A :class:`Response` ``(status, body)``."
 },
 {
  "label": "bugbuster.mqtt_publish",
  "snippet": "bugbuster.mqtt_publish(${topic}, ${payload}, ${host})",
  "type": "function",
  "detail": "Publish one MQTT message (QoS 0, not retained) and disconnect.",
  "info": "Publish one MQTT message (QoS 0, not retained) and disconnect.\ntopic: Topic string.\npayload: Message bytes or text.\nhost: Broker host name or IP address.\nport: Broker TCP port, 1-65535. Default 1883.\nusername: Optional user name.\npassword: Optional password."
 },
 {
  "label": "bugbuster.claim",
  "snippet": "bugbuster.claim(${slots})",
  "type": "function",
  "detail": "Create a claim on IO slots; use it as ``with claim([...]):``.",
  "info": "Create a claim on IO slots; use it as ``with claim([...]):``.\nslots: 1-16 slot numbers: 0-11 for IO1-IO12, 12-15 for CH0-CH3.\npurpose: Free-text label recorded with the claim.\nlease_ms: Lease in milliseconds; 0 (default) holds until released.\nreturns: A :class:`Claim` context manager."
 },
 {
  "label": "bugbuster.release",
  "snippet": "bugbuster.release()",
  "type": "function",
  "detail": "Release slots held by this script immediately.",
  "info": "Release slots held by this script immediately.\nslots: Slot numbers to release; None (default) releases every slot this script holds."
 },
 {
  "label": "bugbuster.owner_status",
  "snippet": "bugbuster.owner_status()",
  "type": "function",
  "detail": "Return the ownership table of all 16 slots.",
  "info": "Return the ownership table of all 16 slots.\nreturns: A list of 16 dicts, index = slot number."
 },
 {
  "label": "bugbuster.hat_status",
  "snippet": "bugbuster.hat_status()",
  "type": "function",
  "detail": "Return the HAT detection, link and firmware state. Works without a HAT.",
  "info": "Return the HAT detection, link and firmware state. Works without a HAT.\nreturns: A dict describing the HAT."
 },
 {
  "label": "bugbuster.hat_caps",
  "snippet": "bugbuster.hat_caps()",
  "type": "function",
  "detail": "Return the HAT capabilities.",
  "info": "Return the HAT capabilities.\nreturns: A dict describing what the HAT hardware offers."
 },
 {
  "label": "bugbuster.hat_rails",
  "snippet": "bugbuster.hat_rails()",
  "type": "function",
  "detail": "Return the state of the HAT rails.",
  "info": "Return the state of the HAT rails.\nreturns: One dict per rail, in ``HAT_RAIL_*`` order."
 },
 {
  "label": "bugbuster.hat_set_rail_enable",
  "snippet": "bugbuster.hat_set_rail_enable(${rail}, ${enable})",
  "type": "function",
  "detail": "Switch a HAT rail on or off.",
  "info": "Switch a HAT rail on or off.\nrail: A ``HAT_RAIL_*`` value, 0-2.\nenable: True to enable the rail."
 },
 {
  "label": "bugbuster.hat_set_rail_voltage",
  "snippet": "bugbuster.hat_set_rail_voltage(${rail}, ${mv})",
  "type": "function",
  "detail": "Set a HAT rail voltage.",
  "info": "Set a HAT rail voltage.\nrail: A ``HAT_RAIL_*`` value, 0-2.\nmv: Voltage in millivolts, 0-36000."
 },
 {
  "label": "bugbuster.hat_led",
  "snippet": "bugbuster.hat_led(${led}, ${color})",
  "type": "function",
  "detail": "Set a HAT LED colour.",
  "info": "Set a HAT LED colour.\nled: LED number, 1-8.\ncolor: A ``HAT_LED_*`` code (0-7), or any code 0-255 the HAT accepts."
 },
 {
  "label": "bugbuster.hat_io_bank",
  "snippet": "bugbuster.hat_io_bank(${dirs})",
  "type": "function",
  "detail": "Configure the HAT's 8-bit I/O bank; each argument is a bit mask (bit n = pin n).",
  "info": "Configure the HAT's 8-bit I/O bank; each argument is a bit mask (bit n = pin n).\ndirs: Direction mask, 1 = output.\nups: Pull-up mask, 1 = pull-up enabled. Default 0.\ndns: Pull-down mask, 1 = pull-down enabled. Default 0.\nvals: Output level mask for the pins set to output. Default 0."
 },
 {
  "label": "bugbuster.hat_level_shift",
  "snippet": "bugbuster.hat_level_shift(${oe}, ${dir})",
  "type": "function",
  "detail": "Set the HAT level-shifter output enable and direction.",
  "info": "Set the HAT level-shifter output enable and direction.\noe: True enables the shifter outputs.\ndir: Direction, any truthy value selects one way, 0 the other.\nreturns: A dict with the state the HAT applied."
 },
 {
  "label": "bugbuster.hat_calibrate_start",
  "snippet": "bugbuster.hat_calibrate_start(${rail})",
  "type": "function",
  "detail": "Start the calibration of a HAT rail.",
  "info": "Start the calibration of a HAT rail.\nrail: A ``HAT_RAIL_*`` value, 0-2.\nreturns: The status byte the HAT returned for the start request."
 },
 {
  "label": "bugbuster.hat_calibrate_status",
  "snippet": "bugbuster.hat_calibrate_status()",
  "type": "function",
  "detail": "Return the calibration progress and result.",
  "info": "Return the calibration progress and result.\nreturns: A dict with the calibration state."
 },
 {
  "label": "bugbuster.hat_calibrate_import",
  "snippet": "bugbuster.hat_calibrate_import(${rail}, ${points})",
  "type": "function",
  "detail": "Load calibration points into a HAT rail.",
  "info": "Load calibration points into a HAT rail.\nrail: A ``HAT_RAIL_*`` value, 0-2.\npoints: 2-6 ``(dac_code, measured_v)`` pairs; ``dac_code`` is an integer -128..127, ``measured_v`` the voltage you measured in volts."
 },
 {
  "label": "bugbuster.hat_setup_swd",
  "snippet": "bugbuster.hat_setup_swd()",
  "type": "function",
  "detail": "Power the SWD target connector and set the HAT I/O voltage.",
  "info": "Power the SWD target connector and set the HAT I/O voltage.\ntarget_voltage_mv: Target voltage in millivolts, 1200-5500. Default 3300.\nconnector: 0 for connector A (VADJ1), 1 for connector B (VADJ2). Default 0."
 },
 {
  "label": "bugbuster.FUNC_HIGH_IMP",
  "snippet": "bugbuster.FUNC_HIGH_IMP",
  "type": "constant",
  "detail": "Channel function 0: high impedance. The safe resting state; use it to release an output.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_VOUT",
  "snippet": "bugbuster.FUNC_VOUT",
  "type": "constant",
  "detail": "Channel function 1: voltage output. ``Channel.set_voltage`` drives the terminal.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_IOUT",
  "snippet": "bugbuster.FUNC_IOUT",
  "type": "constant",
  "detail": "Channel function 2: current output (externally powered).",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_VIN",
  "snippet": "bugbuster.FUNC_VIN",
  "type": "constant",
  "detail": "Channel function 3: voltage input (ADC). Use with ``Channel.read_voltage``.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_IIN_EXT_PWR",
  "snippet": "bugbuster.FUNC_IIN_EXT_PWR",
  "type": "constant",
  "detail": "Channel function 4: current input, externally powered loop.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_IIN_LOOP_PWR",
  "snippet": "bugbuster.FUNC_IIN_LOOP_PWR",
  "type": "constant",
  "detail": "Channel function 5: current input, loop powered by the board.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_RES_MEAS",
  "snippet": "bugbuster.FUNC_RES_MEAS",
  "type": "constant",
  "detail": "Channel function 7: resistance measurement (RTD).",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_DIN_LOGIC",
  "snippet": "bugbuster.FUNC_DIN_LOGIC",
  "type": "constant",
  "detail": "Channel function 8: digital input, logic level.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_DIN_LOOP",
  "snippet": "bugbuster.FUNC_DIN_LOOP",
  "type": "constant",
  "detail": "Channel function 9: digital input, loop powered.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_IOUT_HART",
  "snippet": "bugbuster.FUNC_IOUT_HART",
  "type": "constant",
  "detail": "Channel function 10: current output with HART.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_IIN_EXT_PWR_HART",
  "snippet": "bugbuster.FUNC_IIN_EXT_PWR_HART",
  "type": "constant",
  "detail": "Channel function 11: current input, externally powered, with HART.",
  "info": ""
 },
 {
  "label": "bugbuster.FUNC_IIN_LOOP_PWR_HART",
  "snippet": "bugbuster.FUNC_IIN_LOOP_PWR_HART",
  "type": "constant",
  "detail": "Channel function 12: current input, loop powered, with HART.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_RAIL_3V3_ADJ",
  "snippet": "bugbuster.HAT_RAIL_3V3_ADJ",
  "type": "constant",
  "detail": "HAT rail 0: the adjustable I/O voltage rail (its \"voltage\" is the HAT I/O level).",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_RAIL_VADJ3",
  "snippet": "bugbuster.HAT_RAIL_VADJ3",
  "type": "constant",
  "detail": "HAT rail 1: VADJ3, a buck-boost target supply.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_RAIL_VADJ4",
  "snippet": "bugbuster.HAT_RAIL_VADJ4",
  "type": "constant",
  "detail": "HAT rail 2: VADJ4, a buck-boost target supply.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_OFF",
  "snippet": "bugbuster.HAT_LED_OFF",
  "type": "constant",
  "detail": "HAT LED colour 0: off.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_RED",
  "snippet": "bugbuster.HAT_LED_RED",
  "type": "constant",
  "detail": "HAT LED colour 1: red.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_GREEN",
  "snippet": "bugbuster.HAT_LED_GREEN",
  "type": "constant",
  "detail": "HAT LED colour 2: green.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_BLUE",
  "snippet": "bugbuster.HAT_LED_BLUE",
  "type": "constant",
  "detail": "HAT LED colour 3: blue.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_YELLOW",
  "snippet": "bugbuster.HAT_LED_YELLOW",
  "type": "constant",
  "detail": "HAT LED colour 4: yellow.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_CYAN",
  "snippet": "bugbuster.HAT_LED_CYAN",
  "type": "constant",
  "detail": "HAT LED colour 5: cyan.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_MAGENTA",
  "snippet": "bugbuster.HAT_LED_MAGENTA",
  "type": "constant",
  "detail": "HAT LED colour 6: magenta.",
  "info": ""
 },
 {
  "label": "bugbuster.HAT_LED_WHITE",
  "snippet": "bugbuster.HAT_LED_WHITE",
  "type": "constant",
  "detail": "HAT LED colour 7: white.",
  "info": ""
 },
 {
  "label": "bugbuster.Channel",
  "snippet": "bugbuster.Channel(${channel})",
  "type": "class",
  "detail": "One analog channel of the AD74416H front-end (CH0-CH3).",
  "info": "Create a handle for one channel. Does not change the hardware.\nchannel: Channel index, 0-3."
 },
 {
  "label": "bugbuster.I2C",
  "snippet": "bugbuster.I2C(${sda_io}, ${scl_io})",
  "type": "class",
  "detail": "External I2C master on two IO terminals (not raw ESP32 GPIOs).",
  "info": "Open the bus and power the IO block.\nsda_io: IO terminal for SDA, 1-12.\nscl_io: IO terminal for SCL, 1-12; must differ from ``sda_io``.\nfreq: Clock in Hz. Default 400000. Use external pull-ups from 400 kHz up.\npullups: 'external' (default), 'internal' or 'off'. 'off' behaves like 'external': only 'internal' enables the board's pull-ups.\nsupply: VADJ rail voltage for the IO block in volts, 3.0-15.0. Default 3.3.\nvlogic: Logic level in volts. Default 3.3.\nallow_split_supplies: True permits SDA and SCL on different rails (IO1-6 vs IO7-12). Default False."
 },
 {
  "label": "bugbuster.SPI",
  "snippet": "bugbuster.SPI(${sck_io})",
  "type": "class",
  "detail": "External SPI master on IO terminals (not raw ESP32 GPIOs).",
  "info": "Open the bus and power the IO block.\nsck_io: IO terminal for the clock, 1-12.\nmosi_io: IO terminal for MOSI, 1-12, or None to omit.\nmiso_io: IO terminal for MISO, 1-12, or None to omit.\ncs_io: IO terminal for chip select, 1-12, or None to omit.\nfreq: Clock in Hz. Default 1000000.\nmode: SPI mode 0-3 (clock polarity and phase). Default 0.\nsupply: VADJ rail voltage for the IO block in volts, 3.0-15.0. Default 3.3.\nvlogic: Logic level in volts. Default 3.3.\nallow_split_supplies: True permits pins on different rails. Default False."
 },
 {
  "label": "bugbuster.Response",
  "snippet": "bugbuster.Response()",
  "type": "class",
  "detail": "HTTP result returned by :func:`http_get` and :func:`http_post`.",
  "info": "HTTP result returned by :func:`http_get` and :func:`http_post`."
 },
 {
  "label": "bugbuster.Response.status",
  "snippet": "bugbuster.Response.status",
  "type": "constant",
  "detail": "HTTP status code, for example 200.",
  "info": ""
 },
 {
  "label": "bugbuster.Response.body",
  "snippet": "bugbuster.Response.body",
  "type": "constant",
  "detail": "Response body as bytes. Use ``body.decode()`` for text.",
  "info": ""
 },
 {
  "label": "bugbuster.Claim",
  "snippet": "bugbuster.Claim()",
  "type": "class",
  "detail": "Context manager returned by :func:`claim`; acquires on entry, releases on exit.",
  "info": "Context manager returned by :func:`claim`; acquires on entry, releases on exit."
 },
 {
  "label": "daq",
  "snippet": "daq",
  "type": "namespace",
  "detail": "DAQ HAT control from on-device scripts: the VDUT programmable supply and the",
  "info": "DAQ HAT control from on-device scripts: the VDUT programmable supply and the"
 },
 {
  "label": "daq.present",
  "snippet": "daq.present()",
  "type": "function",
  "detail": "Report whether a DAQ HAT is connected. Never raises.",
  "info": "Report whether a DAQ HAT is connected. Never raises.\nreturns: True when a DAQ HAT is connected and answering."
 },
 {
  "label": "daq.vdut",
  "snippet": "daq.vdut()",
  "type": "function",
  "detail": "Set the VDUT supply (setpoint, current limit, output) and return its state.",
  "info": "Set the VDUT supply (setpoint, current limit, output) and return its state.\nenable: True switches the output on, False off, None leaves it as it is.\nvolts: Output setpoint in volts, 1.76-19.94.\namps_limit: Current limit in amps, 0.05-2.636.\nreturns: A dict with the supply state after the change."
 },
 {
  "label": "daq.read",
  "snippet": "daq.read()",
  "type": "function",
  "detail": "Measure the DUT output of the VDUT supply.",
  "info": "Measure the DUT output of the VDUT supply.\nreturns: A dict with the live measurement."
 },
 {
  "label": "daq.samples",
  "snippet": "daq.samples(${run_id})",
  "type": "function",
  "detail": "Fetch the live 1 s samples of the loaded battery-simulator run.",
  "info": "Fetch the live 1 s samples of the loaded battery-simulator run.\nrun_id: Run id, 1-65535; must be the loaded run.\nsince_s: Return samples with a time newer than this many simulated seconds. Default 0.\nmax: Maximum number of samples, 1-3600. Default 600.\nreturns: A list of ``(t_s, v, i, soc, flags)`` tuples: interval end in simulated seconds, mean voltage in volts, mean current in amps, state of charge in percent, and history flags (bit mask: 1 gap, 2 current clamp, 4 resume, 8 output off, 16 below cutoff)."
 },
 {
  "label": "daq.run",
  "snippet": "daq.run",
  "type": "namespace",
  "detail": "Battery-simulator runs. A namespace: call as ``daq.run.status()``.",
  "info": "Battery-simulator runs. A namespace: call as ``daq.run.status()``."
 },
 {
  "label": "daq.run.status",
  "snippet": "daq.run.status()",
  "type": "function",
  "detail": "Report the loaded run and the simulator state.",
  "info": "Report the loaded run and the simulator state.\nreturns: A dict describing the loaded run."
 },
 {
  "label": "daq.run.list",
  "snippet": "daq.run.list()",
  "type": "function",
  "detail": "List every stored run.",
  "info": "List every stored run.\nreturns: One dict per run."
 },
 {
  "label": "daq.run.new",
  "snippet": "daq.run.new(${name}, ${chem}, ${cells}, ${capacity_mah})",
  "type": "function",
  "detail": "Create a run, load it (paused, output off) and return its id.",
  "info": "Create a run, load it (paused, output off) and return its id.\nname: Run name, at most 23 bytes.\nchem: Chemistry: 'lipo', 'lifepo4', 'nimh' or 'lead' (or the number 0-3 in that order).\ncells: Cells in series.\ncapacity_mah: Capacity in milliamp-hours.\nsoc: Starting state of charge in percent. Default 100.\nself_discharge: Self-discharge in percent per month; None (default) disables it.\next_load: Extra virtual load in microamps; None (default) disables it.\nreturns: The new run id."
 },
 {
  "label": "daq.run.start",
  "snippet": "daq.run.start()",
  "type": "function",
  "detail": "Start the run, or resume it from pause.",
  "info": "Start the run, or resume it from pause.\nrun_id: Load this run first; None (default) starts the loaded run."
 },
 {
  "label": "daq.run.pause",
  "snippet": "daq.run.pause()",
  "type": "function",
  "detail": "Switch the output off and freeze the run.",
  "info": "Switch the output off and freeze the run."
 },
 {
  "label": "daq.run.stop",
  "snippet": "daq.run.stop()",
  "type": "function",
  "detail": "Finalise the run; its data stays on the HAT.",
  "info": "Finalise the run; its data stays on the HAT."
 },
 {
  "label": "daq.run.reopen",
  "snippet": "daq.run.reopen()",
  "type": "function",
  "detail": "Resume a stopped run: it returns to 'paused' with the output off.",
  "info": "Resume a stopped run: it returns to 'paused' with the output off.\nrun_id: Load this run first; None (default) uses the loaded run."
 },
 {
  "label": "daq.run.edit",
  "snippet": "daq.run.edit()",
  "type": "function",
  "detail": "Change parameters of the loaded run while it is live.",
  "info": "Change parameters of the loaded run while it is live.\nrun_id: Load this run first; None (default) edits the loaded run.\nparams: Parameters to change: name (str, <= 23 bytes); chem ('lipo' | 'lifepo4' | 'nimh' | 'lead'); cells (int); capacity_mah (int); soc (percent); cutoff_mv_cell (millivolts per cell); rint_uohm_cell (internal resistance in micro-ohms per cell); peukert (exponent); self_discharge (percent per month, None/0 disables); ext_load (microamps, None/0 disables); dither (bool).\nreturns: The run status, as :func:`status`."
 },
 {
  "label": "daq.run.delete",
  "snippet": "daq.run.delete(${run_id})",
  "type": "function",
  "detail": "Delete a stored run and its data.",
  "info": "Delete a stored run and its data.\nrun_id: Run id, 1-65535."
 },
 {
  "label": "machine",
  "snippet": "machine",
  "type": "namespace",
  "detail": "MicroPython ``machine`` on BugBuster: ESP32-S3 GPIO pins, bit-banged I2C/SPI,",
  "info": "MicroPython ``machine`` on BugBuster: ESP32-S3 GPIO pins, bit-banged I2C/SPI,"
 },
 {
  "label": "machine.reset",
  "snippet": "machine.reset()",
  "type": "function",
  "detail": "Hard-reboot the board (the ESP32 restarts).",
  "info": "Hard-reboot the board (the ESP32 restarts)."
 },
 {
  "label": "machine.soft_reset",
  "snippet": "machine.soft_reset()",
  "type": "function",
  "detail": "End the script (an alias of ``sys.exit``).",
  "info": "End the script (an alias of ``sys.exit``)."
 },
 {
  "label": "machine.reset_cause",
  "snippet": "machine.reset_cause()",
  "type": "function",
  "detail": "Return why the chip last reset (the ESP-IDF ``esp_reset_reason()`` code).",
  "info": "Return why the chip last reset (the ESP-IDF ``esp_reset_reason()`` code).\nreturns: 1 power-on, 2 external pin, 3 software, 4 panic, 5 interrupt watchdog, 6 task watchdog, 7 other watchdog, 8 deep sleep wake, 9 brown-out, 10 SDIO; 0 when unknown."
 },
 {
  "label": "machine.unique_id",
  "snippet": "machine.unique_id()",
  "type": "function",
  "detail": "Return the Wi-Fi station MAC address as 6 bytes, unique per board.",
  "info": "Return the Wi-Fi station MAC address as 6 bytes, unique per board.\nreturns: 6 bytes."
 },
 {
  "label": "machine.freq",
  "snippet": "machine.freq()",
  "type": "function",
  "detail": "Return the CPU frequency in Hz. Read-only: ``freq(hz)`` raises ``NotImplementedError``.",
  "info": "Return the CPU frequency in Hz. Read-only: ``freq(hz)`` raises ``NotImplementedError``.\nreturns: Frequency in hertz."
 },
 {
  "label": "machine.idle",
  "snippet": "machine.idle()",
  "type": "function",
  "detail": "Yield the CPU to other tasks for one scheduler tick.",
  "info": "Yield the CPU to other tasks for one scheduler tick."
 },
 {
  "label": "machine.lightsleep",
  "snippet": "machine.lightsleep()",
  "type": "function",
  "detail": "Put the chip into light sleep.",
  "info": "Put the chip into light sleep.\ntime_ms: Wake after this many milliseconds. None sleeps with no wake source configured."
 },
 {
  "label": "machine.deepsleep",
  "snippet": "machine.deepsleep()",
  "type": "function",
  "detail": "Put the chip into deep sleep; the board restarts on wake.",
  "info": "Put the chip into deep sleep; the board restarts on wake.\ntime_ms: Wake after this many milliseconds. None sleeps with no wake source configured."
 },
 {
  "label": "machine.Pin",
  "snippet": "machine.Pin(${id})",
  "type": "class",
  "detail": "One ESP32-S3 GPIO (raw GPIO number, 0-48).",
  "info": "Select a GPIO and optionally configure it.\nid: GPIO number, 0-48.\nmode: ``Pin.IN``, ``Pin.OUT`` or ``Pin.OPEN_DRAIN``; None leaves the direction unchanged.\npull: ``Pin.PULL_UP`` or ``Pin.PULL_DOWN``; 0 disables both; None leaves it unchanged.\nvalue: Initial output level, applied before the mode is set."
 },
 {
  "label": "machine.Pin.IN",
  "snippet": "machine.Pin.IN",
  "type": "constant",
  "detail": "Input mode (ESP-IDF GPIO_MODE_INPUT).",
  "info": ""
 },
 {
  "label": "machine.Pin.OUT",
  "snippet": "machine.Pin.OUT",
  "type": "constant",
  "detail": "Output mode that can also be read back (GPIO_MODE_INPUT_OUTPUT).",
  "info": ""
 },
 {
  "label": "machine.Pin.OPEN_DRAIN",
  "snippet": "machine.Pin.OPEN_DRAIN",
  "type": "constant",
  "detail": "Open-drain output, readable (GPIO_MODE_INPUT_OUTPUT_OD).",
  "info": ""
 },
 {
  "label": "machine.Pin.PULL_UP",
  "snippet": "machine.Pin.PULL_UP",
  "type": "constant",
  "detail": "Enable the internal pull-up (disables the pull-down).",
  "info": ""
 },
 {
  "label": "machine.Pin.PULL_DOWN",
  "snippet": "machine.Pin.PULL_DOWN",
  "type": "constant",
  "detail": "Enable the internal pull-down (disables the pull-up).",
  "info": ""
 },
 {
  "label": "machine.SoftI2C",
  "snippet": "machine.SoftI2C(${scl}, ${sda})",
  "type": "class",
  "detail": "Bit-banged I2C master on two ESP GPIOs.",
  "info": "Create the bus on two pins.\nscl: Clock pin.\nsda: Data pin.\nfreq: Clock in Hz. Default 400000.\ntimeout: Clock-stretch timeout in microseconds. Default 255."
 },
 {
  "label": "machine.I2C",
  "snippet": "machine.I2C()",
  "type": "class",
  "detail": "Alias of :class:`SoftI2C` on this port (there is no hardware I2C).",
  "info": "Alias of :class:`SoftI2C` on this port (there is no hardware I2C)."
 },
 {
  "label": "machine.SoftSPI",
  "snippet": "machine.SoftSPI()",
  "type": "class",
  "detail": "Bit-banged SPI master on ESP GPIOs.",
  "info": "Create the bus.\nbaudrate: Clock in Hz. Default 500000.\npolarity: Idle clock level, 0 or 1. Default 0.\nphase: Sampling edge, 0 (first) or 1 (second). Default 0.\nsck: Clock pin.\nmosi: Data-out pin.\nmiso: Data-in pin."
 },
 {
  "label": "machine.SoftSPI.MSB",
  "snippet": "machine.SoftSPI.MSB",
  "type": "constant",
  "detail": "Most significant bit first.",
  "info": ""
 },
 {
  "label": "machine.SoftSPI.LSB",
  "snippet": "machine.SoftSPI.LSB",
  "type": "constant",
  "detail": "Least significant bit first.",
  "info": ""
 },
 {
  "label": "machine.SPI",
  "snippet": "machine.SPI()",
  "type": "class",
  "detail": "Alias of :class:`SoftSPI` on this port (there is no hardware SPI).",
  "info": "Alias of :class:`SoftSPI` on this port (there is no hardware SPI)."
 },
 {
  "label": "machine.WDT",
  "snippet": "machine.WDT()",
  "type": "class",
  "detail": "Watchdog timer: reboots the board when it is not fed in time.",
  "info": "Start the watchdog.\nid: Watchdog number, 0.\ntimeout: Timeout in milliseconds. Default 5000."
 },
 {
  "label": "bb_helpers",
  "snippet": "bb_helpers",
  "type": "namespace",
  "detail": "Small helpers for channel ramps and sweeps (``bb_helpers.py`` on the device).",
  "info": "Small helpers for channel ramps and sweeps (``bb_helpers.py`` on the device)."
 },
 {
  "label": "bb_helpers.settle",
  "snippet": "bb_helpers.settle(${ms})",
  "type": "function",
  "detail": "Wait ``ms`` milliseconds (a thin wrapper over ``bugbuster.sleep``).",
  "info": "Wait ``ms`` milliseconds (a thin wrapper over ``bugbuster.sleep``).\nms: Delay in milliseconds, 0 or more."
 },
 {
  "label": "bb_helpers.dac_ramp",
  "snippet": "bb_helpers.dac_ramp(${channel}, ${lo}, ${hi}, ${step})",
  "type": "function",
  "detail": "Ramp a channel's DAC from ``lo`` to ``hi`` volts and read each step back.",
  "info": "Ramp a channel's DAC from ``lo`` to ``hi`` volts and read each step back.\nchannel: Channel index, 0-3.\nlo: Start voltage in volts (0 to 12 V unipolar).\nhi: End voltage in volts, included.\nstep: Increment in volts; must be greater than 0 (a zero or negative step never ends).\nsettle_ms: Wait after each step in milliseconds. Default 50.\nreturns: A list of ``(set_volts, readback_volts)`` tuples, one per step."
 },
 {
  "label": "bb_helpers.channel_sweep",
  "snippet": "bb_helpers.channel_sweep(${channel}, ${voltages})",
  "type": "function",
  "detail": "Drive a channel through an explicit list of voltages.",
  "info": "Drive a channel through an explicit list of voltages.\nchannel: Channel index, 0-3.\nvoltages: Iterable of voltages in volts.\nsettle_ms: Wait after each step in milliseconds. Default 100.\nreadback: True (default) reads the ADC after each step.\nreturns: With ``readback=True`` a list of ``(target_volts, readback_volts)`` tuples; otherwise a list of the target voltages."
 },
 {
  "label": "bb_devices",
  "snippet": "bb_devices",
  "type": "namespace",
  "detail": "Drivers for common I2C/SPI/1-Wire/display parts (``bb_devices.py`` on the device).",
  "info": "Drivers for common I2C/SPI/1-Wire/display parts (``bb_devices.py`` on the device)."
 },
 {
  "label": "bb_devices.TMP102",
  "snippet": "bb_devices.TMP102(${i2c})",
  "type": "class",
  "detail": "TI TMP102 I2C temperature sensor (12-bit, 0.0625 C per step).",
  "info": "Attach to the sensor. No bus traffic until you read.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x48-0x4B by the ADD0 pin. Default 0x48."
 },
 {
  "label": "bb_devices.BMP280",
  "snippet": "bb_devices.BMP280(${i2c})",
  "type": "class",
  "detail": "Bosch BMP280 pressure/temperature sensor (raw values only).",
  "info": "Check the chip id and start measuring.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x76 or 0x77. Default 0x76."
 },
 {
  "label": "bb_devices.MCP3008",
  "snippet": "bb_devices.MCP3008(${spi})",
  "type": "class",
  "detail": "Microchip MCP3008 / MCP3004 10-bit SPI ADC.",
  "info": "Attach to the converter.\nspi: A ``bugbuster.SPI`` bus with MOSI, MISO and chip select.\nchannels: 8 for the MCP3008, 4 for the MCP3004."
 },
 {
  "label": "bb_devices.DS18B20",
  "snippet": "bb_devices.DS18B20(${pin})",
  "type": "class",
  "detail": "Dallas/Maxim DS18B20 1-Wire temperature sensor.",
  "info": "Set up the 1-Wire bus on a pin.\npin: A ``machine.Pin`` or GPIO number."
 },
 {
  "label": "bb_devices.DS3231",
  "snippet": "bb_devices.DS3231(${i2c})",
  "type": "class",
  "detail": "Maxim DS3231 real-time clock with temperature readback.",
  "info": "Attach to the clock. No bus traffic until you read.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address. Default 0x68."
 },
 {
  "label": "bb_devices.BH1750",
  "snippet": "bb_devices.BH1750(${i2c})",
  "type": "class",
  "detail": "ROHM BH1750 ambient light sensor.",
  "info": "Power the sensor on and reset it.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x23 (ADDR low) or 0x5C. Default 0x23."
 },
 {
  "label": "bb_devices.AHT20",
  "snippet": "bb_devices.AHT20(${i2c})",
  "type": "class",
  "detail": "Aosong AHT20 humidity and temperature sensor.",
  "info": "Reset and initialise the sensor (about 30 ms).\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address. Default 0x38."
 },
 {
  "label": "bb_devices.SHT31",
  "snippet": "bb_devices.SHT31(${i2c})",
  "type": "class",
  "detail": "Sensirion SHT31 temperature and humidity sensor.",
  "info": "Attach to the sensor. No bus traffic until you use it.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x44 or 0x45. Default 0x44."
 },
 {
  "label": "bb_devices.BME280",
  "snippet": "bb_devices.BME280(${i2c})",
  "type": "class",
  "detail": "Bosch BME280 compensated temperature, pressure and humidity sensor.",
  "info": "Check the chip id, load the calibration and start measuring (normal mode).\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x76 or 0x77. Default 0x76."
 },
 {
  "label": "bb_devices.INA219",
  "snippet": "bb_devices.INA219(${i2c})",
  "type": "class",
  "detail": "TI INA219 current and power monitor.",
  "info": "Write the calibration and configuration registers.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x40-0x4F. Default 0x40.\nshunt_ohms: Shunt resistor in ohms. Default 0.1.\nmax_expected_amps: Largest current you expect, in amps; sets the resolution. Default 2.0."
 },
 {
  "label": "bb_devices.ADS1115",
  "snippet": "bb_devices.ADS1115(${i2c})",
  "type": "class",
  "detail": "TI ADS1115 16-bit I2C ADC.",
  "info": "Attach to the converter. No bus traffic until you read.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x48-0x4B by the ADDR pin. Default 0x48."
 },
 {
  "label": "bb_devices.MCP23017",
  "snippet": "bb_devices.MCP23017(${i2c})",
  "type": "class",
  "detail": "Microchip MCP23017 16-bit I2C GPIO expander (pins 0-7 = port A, 8-15 = port B).",
  "info": "Configure the part and set every pin to input.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x20-0x27. Default 0x20."
 },
 {
  "label": "bb_devices.PCF8574",
  "snippet": "bb_devices.PCF8574(${i2c})",
  "type": "class",
  "detail": "NXP PCF8574 8-bit quasi-bidirectional I2C I/O expander.",
  "info": "Attach and write the initial output byte.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x20-0x27 (0x38-0x3F for the PCF8574A). Default 0x20.\nvalue: Initial output byte; 0xFF (default) leaves every pin high/input."
 },
 {
  "label": "bb_devices.PCA9685",
  "snippet": "bb_devices.PCA9685(${i2c})",
  "type": "class",
  "detail": "NXP PCA9685 16-channel 12-bit PWM controller.",
  "info": "Initialise the part and set 50 Hz.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address. Default 0x40.\nosc_hz: Oscillator frequency in Hz. Default 25000000."
 },
 {
  "label": "bb_devices.TCS34725",
  "snippet": "bb_devices.TCS34725(${i2c})",
  "type": "class",
  "detail": "ams OSRAM TCS34725 RGBC colour sensor.",
  "info": "Check the id, set integration time and gain, and enable the sensor.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address. Default 0x29.\nintegration_ms: Integration time in milliseconds, about 2.4-614. Default 50.\ngain: 1, 4, 16 or 60. Default 4."
 },
 {
  "label": "bb_devices.MPU6050",
  "snippet": "bb_devices.MPU6050(${i2c})",
  "type": "class",
  "detail": "InvenSense MPU6050 6-axis accelerometer and gyroscope.",
  "info": "Check the id, wake the part and set the ranges.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x68 or 0x69. Default 0x68.\naccel_range: Full scale in g: 2, 4, 8 or 16. Default 2.\ngyro_range: Full scale in degrees per second: 250, 500, 1000 or 2000. Default 250."
 },
 {
  "label": "bb_devices.MCP4725",
  "snippet": "bb_devices.MCP4725(${i2c})",
  "type": "class",
  "detail": "Microchip MCP4725 12-bit I2C DAC.",
  "info": "Attach to the DAC. No bus traffic until you set an output.\ni2c: A ``bugbuster.I2C`` bus.\naddr: 7-bit address, 0x60-0x67. Default 0x60.\nvref: Supply/reference voltage in volts. Default 3.3."
 },
 {
  "label": "bb_devices.SSD1306_I2C",
  "snippet": "bb_devices.SSD1306_I2C(${width}, ${height}, ${i2c})",
  "type": "class",
  "detail": "SSD1306 OLED display over I2C (the MicroPython ``ssd1306`` driver, frozen into the firmwar",
  "info": "Initialise the display.\nwidth: Pixels, usually 128.\nheight: Pixels, 32 or 64.\ni2c: A bus object with the I2C ``writeto`` method.\naddr: 7-bit address. Default 0x3C.\nexternal_vcc: True when the panel has its own supply. Default False."
 },
 {
  "label": "bb_devices.SSD1306_SPI",
  "snippet": "bb_devices.SSD1306_SPI(${width}, ${height}, ${spi}, ${dc}, ${res}, ${cs})",
  "type": "class",
  "detail": "SSD1306 OLED display over SPI (the MicroPython ``ssd1306`` driver).",
  "info": "Initialise the display.\nwidth: Pixels, usually 128.\nheight: Pixels, 32 or 64.\nspi: SPI bus object (``machine.SoftSPI``).\ndc: Data/command ``machine.Pin``.\nres: Reset ``machine.Pin``.\ncs: Chip-select ``machine.Pin``.\nexternal_vcc: True when the panel has its own supply. Default False."
 },
 {
  "label": "bb_devices.SSD1306",
  "snippet": "bb_devices.SSD1306()",
  "type": "class",
  "detail": "Alias of :class:`SSD1306_I2C`.",
  "info": "Alias of :class:`SSD1306_I2C`."
 },
 {
  "label": "bb_logging",
  "snippet": "bb_logging",
  "type": "namespace",
  "detail": "Timestamped log helpers (``bb_logging.py`` on the device).",
  "info": "Timestamped log helpers (``bb_logging.py`` on the device)."
 },
 {
  "label": "bb_logging.debug",
  "snippet": "bb_logging.debug(${msg})",
  "type": "function",
  "detail": "Log a DEBUG-level line (level 'D') with a timestamp.",
  "info": "Log a DEBUG-level line (level 'D') with a timestamp.\nmsg: Text to log."
 },
 {
  "label": "bb_logging.info",
  "snippet": "bb_logging.info(${msg})",
  "type": "function",
  "detail": "Log an INFO-level line (level 'I') with a timestamp.",
  "info": "Log an INFO-level line (level 'I') with a timestamp.\nmsg: Text to log."
 },
 {
  "label": "bb_logging.warn",
  "snippet": "bb_logging.warn(${msg})",
  "type": "function",
  "detail": "Log a WARN-level line (level 'W') with a timestamp.",
  "info": "Log a WARN-level line (level 'W') with a timestamp.\nmsg: Text to log."
 },
 {
  "label": "bb_logging.error",
  "snippet": "bb_logging.error(${msg})",
  "type": "function",
  "detail": "Log an ERROR-level line (level 'E') with a timestamp.",
  "info": "Log an ERROR-level line (level 'E') with a timestamp.\nmsg: Text to log."
 },
 {
  "label": "set_function",
  "snippet": "set_function(${func})",
  "type": "method",
  "detail": "Channel.set_function: Select the channel function (one of the ``FUNC_*`` constants).",
  "info": "Select the channel function (one of the ``FUNC_*`` constants).\nfunc: A ``FUNC_*`` constant (0-5 or 7-12)."
 },
 {
  "label": "set_voltage",
  "snippet": "set_voltage(${voltage})",
  "type": "method",
  "detail": "Channel.set_voltage: Set the DAC output voltage (the channel must be in ``FUNC_VOUT``).",
  "info": "Set the DAC output voltage (the channel must be in ``FUNC_VOUT``).\nvoltage: Output in volts. Unipolar 0 to 12 V; bipolar -12 to +12 V.\nbipolar: True selects the bipolar range. Default False."
 },
 {
  "label": "read_voltage",
  "snippet": "read_voltage()",
  "type": "method",
  "detail": "Channel.read_voltage: Return the latest ADC reading of the channel in volts.",
  "info": "Return the latest ADC reading of the channel in volts.\nreturns: Voltage in volts."
 },
 {
  "label": "set_do",
  "snippet": "set_do(${value})",
  "type": "method",
  "detail": "Channel.set_do: Set the channel's digital output on or off.",
  "info": "Set the channel's digital output on or off.\nvalue: True for logic high, False for low."
 },
 {
  "label": "close",
  "snippet": "close()",
  "type": "method",
  "detail": "I2C.close: Release the bus controller and its IO terminals.",
  "info": "Release the bus controller and its IO terminals."
 },
 {
  "label": "scan",
  "snippet": "scan()",
  "type": "method",
  "detail": "I2C.scan: Probe the address range and return the 7-bit addresses that ACK.",
  "info": "Probe the address range and return the 7-bit addresses that ACK.\nstart: First address to probe. Default 0x08.\nstop: Last address to probe. Default 0x77.\nskip_reserved: Skip reserved address blocks. Default True.\ntimeout_ms: Per-transaction timeout in milliseconds. Default 50.\nreturns: Sorted list of responding 7-bit addresses."
 },
 {
  "label": "writeto",
  "snippet": "writeto(${addr}, ${buf})",
  "type": "method",
  "detail": "I2C.writeto: Write ``buf`` to the device at ``addr``.",
  "info": "Write ``buf`` to the device at ``addr``.\naddr: 7-bit device address.\nbuf: bytes, bytearray or other buffer to send.\ntimeout_ms: Timeout in milliseconds. Default 50."
 },
 {
  "label": "readfrom",
  "snippet": "readfrom(${addr}, ${n})",
  "type": "method",
  "detail": "I2C.readfrom: Read ``n`` bytes from the device at ``addr``.",
  "info": "Read ``n`` bytes from the device at ``addr``.\naddr: 7-bit device address.\nn: Byte count, 1-512.\ntimeout_ms: Timeout in milliseconds. Default 50.\nreturns: The bytes read."
 },
 {
  "label": "writeto_then_readfrom",
  "snippet": "writeto_then_readfrom(${addr}, ${buf}, ${rd_n})",
  "type": "method",
  "detail": "I2C.writeto_then_readfrom: Write ``buf`` then read ``rd_n`` bytes with a repeated start.",
  "info": "Write ``buf`` then read ``rd_n`` bytes with a repeated start.\naddr: 7-bit device address.\nbuf: Bytes to write first (typically the register address).\nrd_n: Byte count to read, 1-512.\ntimeout_ms: Timeout in milliseconds. Default 50.\nreturns: The bytes read."
 },
 {
  "label": "transfer",
  "snippet": "transfer(${buf})",
  "type": "method",
  "detail": "SPI.transfer: Clock ``buf`` out and return the bytes clocked in (full duplex).",
  "info": "Clock ``buf`` out and return the bytes clocked in (full duplex).\nbuf: Bytes to send, 1-512. The reply has the same length.\nreturns: The bytes received while sending."
 },
 {
  "label": "status",
  "snippet": "status()",
  "type": "method",
  "detail": "run.status: Report the loaded run and the simulator state.",
  "info": "Report the loaded run and the simulator state.\nreturns: A dict describing the loaded run."
 },
 {
  "label": "list",
  "snippet": "list()",
  "type": "method",
  "detail": "run.list: List every stored run.",
  "info": "List every stored run.\nreturns: One dict per run."
 },
 {
  "label": "new",
  "snippet": "new(${name}, ${chem}, ${cells}, ${capacity_mah})",
  "type": "method",
  "detail": "run.new: Create a run, load it (paused, output off) and return its id.",
  "info": "Create a run, load it (paused, output off) and return its id.\nname: Run name, at most 23 bytes.\nchem: Chemistry: 'lipo', 'lifepo4', 'nimh' or 'lead' (or the number 0-3 in that order).\ncells: Cells in series.\ncapacity_mah: Capacity in milliamp-hours.\nsoc: Starting state of charge in percent. Default 100.\nself_discharge: Self-discharge in percent per month; None (default) disables it.\next_load: Extra virtual load in microamps; None (default) disables it.\nreturns: The new run id."
 },
 {
  "label": "start",
  "snippet": "start()",
  "type": "method",
  "detail": "run.start: Start the run, or resume it from pause.",
  "info": "Start the run, or resume it from pause.\nrun_id: Load this run first; None (default) starts the loaded run."
 },
 {
  "label": "pause",
  "snippet": "pause()",
  "type": "method",
  "detail": "run.pause: Switch the output off and freeze the run.",
  "info": "Switch the output off and freeze the run."
 },
 {
  "label": "stop",
  "snippet": "stop()",
  "type": "method",
  "detail": "run.stop: Finalise the run; its data stays on the HAT.",
  "info": "Finalise the run; its data stays on the HAT."
 },
 {
  "label": "reopen",
  "snippet": "reopen()",
  "type": "method",
  "detail": "run.reopen: Resume a stopped run: it returns to 'paused' with the output off.",
  "info": "Resume a stopped run: it returns to 'paused' with the output off.\nrun_id: Load this run first; None (default) uses the loaded run."
 },
 {
  "label": "edit",
  "snippet": "edit()",
  "type": "method",
  "detail": "run.edit: Change parameters of the loaded run while it is live.",
  "info": "Change parameters of the loaded run while it is live.\nrun_id: Load this run first; None (default) edits the loaded run.\nparams: Parameters to change: name (str, <= 23 bytes); chem ('lipo' | 'lifepo4' | 'nimh' | 'lead'); cells (int); capacity_mah (int); soc (percent); cutoff_mv_cell (millivolts per cell); rint_uohm_cell (internal resistance in micro-ohms per cell); peukert (exponent); self_discharge (percent per month, None/0 disables); ext_load (microamps, None/0 disables); dither (bool).\nreturns: The run status, as :func:`status`."
 },
 {
  "label": "delete",
  "snippet": "delete(${run_id})",
  "type": "method",
  "detail": "run.delete: Delete a stored run and its data.",
  "info": "Delete a stored run and its data.\nrun_id: Run id, 1-65535."
 },
 {
  "label": "init",
  "snippet": "init()",
  "type": "method",
  "detail": "Pin.init: Reconfigure the pin; the arguments are as for the constructor.",
  "info": "Reconfigure the pin; the arguments are as for the constructor.\nmode: ``Pin.IN``, ``Pin.OUT`` or ``Pin.OPEN_DRAIN``; None leaves it unchanged.\npull: ``Pin.PULL_UP``, ``Pin.PULL_DOWN``, 0 for none; None leaves it unchanged.\nvalue: Output level to set first."
 },
 {
  "label": "value",
  "snippet": "value()",
  "type": "method",
  "detail": "Pin.value: Read the level, or drive it when ``x`` is given.",
  "info": "Read the level, or drive it when ``x`` is given.\nx: 0 or 1 to set the output level; omit to read.\nreturns: The level 0 or 1 when reading; None when setting."
 },
 {
  "label": "on",
  "snippet": "on()",
  "type": "method",
  "detail": "Pin.on: Drive the pin high.",
  "info": "Drive the pin high."
 },
 {
  "label": "off",
  "snippet": "off()",
  "type": "method",
  "detail": "Pin.off: Drive the pin low.",
  "info": "Drive the pin low."
 },
 {
  "label": "readfrom_into",
  "snippet": "readfrom_into(${addr}, ${buf})",
  "type": "method",
  "detail": "SoftI2C.readfrom_into: Read into ``buf`` (its length sets the byte count).",
  "info": "Read into ``buf`` (its length sets the byte count).\naddr: 7-bit address.\nbuf: Destination buffer.\nstop: Send a stop condition afterwards. Default True."
 },
 {
  "label": "readfrom_mem",
  "snippet": "readfrom_mem(${addr}, ${memaddr}, ${nbytes})",
  "type": "method",
  "detail": "SoftI2C.readfrom_mem: Read ``nbytes`` starting at register ``memaddr``.",
  "info": "Read ``nbytes`` starting at register ``memaddr``.\naddr: 7-bit address.\nmemaddr: Register or memory address.\nnbytes: Byte count.\naddrsize: Width of ``memaddr`` in bits. Default 8.\nreturns: The bytes read."
 },
 {
  "label": "writeto_mem",
  "snippet": "writeto_mem(${addr}, ${memaddr}, ${buf})",
  "type": "method",
  "detail": "SoftI2C.writeto_mem: Write ``buf`` starting at register ``memaddr``.",
  "info": "Write ``buf`` starting at register ``memaddr``.\naddr: 7-bit address.\nmemaddr: Register or memory address.\nbuf: Bytes to write.\naddrsize: Width of ``memaddr`` in bits. Default 8."
 },
 {
  "label": "read",
  "snippet": "read(${nbytes})",
  "type": "method",
  "detail": "SoftSPI.read: Read ``nbytes`` while sending the byte ``write`` repeatedly.",
  "info": "Read ``nbytes`` while sending the byte ``write`` repeatedly.\nnbytes: Byte count.\nwrite: Filler byte to send. Default 0.\nreturns: The bytes read."
 },
 {
  "label": "write",
  "snippet": "write(${buf})",
  "type": "method",
  "detail": "SoftSPI.write: Send ``buf`` and ignore the reply.",
  "info": "Send ``buf`` and ignore the reply.\nbuf: Bytes to send."
 },
 {
  "label": "write_readinto",
  "snippet": "write_readinto(${write_buf}, ${read_buf})",
  "type": "method",
  "detail": "SoftSPI.write_readinto: Send ``write_buf`` while reading into ``read_buf`` (same length).",
  "info": "Send ``write_buf`` while reading into ``read_buf`` (same length).\nwrite_buf: Bytes to send.\nread_buf: Buffer that receives the reply."
 },
 {
  "label": "feed",
  "snippet": "feed()",
  "type": "method",
  "detail": "WDT.feed: Restart the timeout. Call it more often than ``timeout``.",
  "info": "Restart the timeout. Call it more often than ``timeout``."
 },
 {
  "label": "read_celsius",
  "snippet": "read_celsius()",
  "type": "method",
  "detail": "TMP102.read_celsius: Read the temperature.",
  "info": "Read the temperature.\nreturns: Temperature in degrees Celsius."
 },
 {
  "label": "roms",
  "snippet": "roms()",
  "type": "method",
  "detail": "DS18B20.roms: Alias of :meth:`scan`.",
  "info": "Alias of :meth:`scan`.\nreturns: A list of 8-byte ROM codes."
 },
 {
  "label": "read_all",
  "snippet": "read_all()",
  "type": "method",
  "detail": "DS18B20.read_all: Convert and read every sensor on the bus with one conversion.",
  "info": "Convert and read every sensor on the bus with one conversion.\nwait_ms: Conversion wait in milliseconds. Default 750.\nreturns: A list of ``(rom, celsius)`` tuples; empty when no sensor is found."
 },
 {
  "label": "clear_osf",
  "snippet": "clear_osf()",
  "type": "method",
  "detail": "DS3231.clear_osf: Clear the oscillator-stop flag after setting the time.",
  "info": "Clear the oscillator-stop flag after setting the time."
 },
 {
  "label": "temperature_c",
  "snippet": "temperature_c()",
  "type": "method",
  "detail": "DS3231.temperature_c: Read the internal temperature sensor.",
  "info": "Read the internal temperature sensor.\nreturns: Temperature in degrees Celsius (0.25 C resolution)."
 },
 {
  "label": "read_datetime",
  "snippet": "read_datetime()",
  "type": "method",
  "detail": "DS3231.read_datetime: Read the date and time.",
  "info": "Read the date and time.\nreturns: ``(year, month, day, weekday, hour, minute, second)``; year is 2000-2099."
 },
 {
  "label": "set_datetime",
  "snippet": "set_datetime(${year}, ${month}, ${day}, ${weekday}, ${hour}, ${minute}, ${second})",
  "type": "method",
  "detail": "DS3231.set_datetime: Set the date and time (24-hour clock).",
  "info": "Set the date and time (24-hour clock).\nyear: Four-digit year; only the last two digits are stored.\nmonth: 1-12.\nday: 1-31.\nweekday: 1-7 (your own convention, stored as given).\nhour: 0-23.\nminute: 0-59.\nsecond: 0-59."
 },
 {
  "label": "power_on",
  "snippet": "power_on()",
  "type": "method",
  "detail": "BH1750.power_on: Wake the sensor.",
  "info": "Wake the sensor."
 },
 {
  "label": "power_down",
  "snippet": "power_down()",
  "type": "method",
  "detail": "BH1750.power_down: Put the sensor in its low-power state.",
  "info": "Put the sensor in its low-power state."
 },
 {
  "label": "reset",
  "snippet": "reset()",
  "type": "method",
  "detail": "BH1750.reset: Clear the data register (the sensor must be powered on).",
  "info": "Clear the data register (the sensor must be powered on)."
 },
 {
  "label": "set_mtreg",
  "snippet": "set_mtreg(${mtreg})",
  "type": "method",
  "detail": "BH1750.set_mtreg: Set the measurement-time register (sensitivity).",
  "info": "Set the measurement-time register (sensitivity).\nmtreg: 31-254, clamped. Default hardware value is 69.\nreturns: The value actually applied."
 },
 {
  "label": "read_lux",
  "snippet": "read_lux()",
  "type": "method",
  "detail": "BH1750.read_lux: Measure the illuminance.",
  "info": "Measure the illuminance.\nhigh_res: True (default) for 1 lx resolution, False for 4 lx.\none_time: True (default) for one-shot, False for continuous mode.\nmtreg: Measurement-time register, 31-254. Default 69.\nreturns: Illuminance in lux."
 },
 {
  "label": "initialize",
  "snippet": "initialize()",
  "type": "method",
  "detail": "AHT20.initialize: Send the initialisation command.",
  "info": "Send the initialisation command."
 },
 {
  "label": "read_temperature",
  "snippet": "read_temperature()",
  "type": "method",
  "detail": "AHT20.read_temperature: Measure and return only the temperature.",
  "info": "Measure and return only the temperature.\nreturns: Temperature in degrees Celsius."
 },
 {
  "label": "read_humidity",
  "snippet": "read_humidity()",
  "type": "method",
  "detail": "AHT20.read_humidity: Measure and return only the humidity.",
  "info": "Measure and return only the humidity.\nreturns: Relative humidity in percent."
 },
 {
  "label": "soft_reset",
  "snippet": "soft_reset()",
  "type": "method",
  "detail": "SHT31.soft_reset: Reset the sensor (2 ms wait).",
  "info": "Reset the sensor (2 ms wait)."
 },
 {
  "label": "read_raw",
  "snippet": "read_raw()",
  "type": "method",
  "detail": "BME280.read_raw: Read the raw ADC values.",
  "info": "Read the raw ADC values.\nreturns: ``(temperature_raw, pressure_raw, humidity_raw)`` uncompensated integers."
 },
 {
  "label": "read_shunt_voltage",
  "snippet": "read_shunt_voltage()",
  "type": "method",
  "detail": "INA219.read_shunt_voltage: Read the voltage across the shunt.",
  "info": "Read the voltage across the shunt.\nreturns: Volts (10 uV per step)."
 },
 {
  "label": "read_bus_voltage",
  "snippet": "read_bus_voltage()",
  "type": "method",
  "detail": "INA219.read_bus_voltage: Read the bus voltage.",
  "info": "Read the bus voltage.\nreturns: Volts (4 mV per step)."
 },
 {
  "label": "read_current",
  "snippet": "read_current()",
  "type": "method",
  "detail": "INA219.read_current: Read the current.",
  "info": "Read the current.\nreturns: Amps, from the calibrated current register."
 },
 {
  "label": "read_power",
  "snippet": "read_power()",
  "type": "method",
  "detail": "INA219.read_power: Read the power.",
  "info": "Read the power.\nreturns: Watts, from the calibrated power register."
 },
 {
  "label": "write_reg",
  "snippet": "write_reg(${reg}, ${value})",
  "type": "method",
  "detail": "MCP23017.write_reg: Write one register.",
  "info": "Write one register.\nreg: Register address.\nvalue: Byte value, 0-255."
 },
 {
  "label": "read_reg",
  "snippet": "read_reg(${reg})",
  "type": "method",
  "detail": "MCP23017.read_reg: Read one register.",
  "info": "Read one register.\nreg: Register address.\nreturns: The byte read."
 },
 {
  "label": "set_direction",
  "snippet": "set_direction(${direction_mask})",
  "type": "method",
  "detail": "MCP23017.set_direction: Set all 16 pin directions.",
  "info": "Set all 16 pin directions.\ndirection_mask: 16-bit mask, bit n = pin n; 1 = input, 0 = output."
 },
 {
  "label": "set_dir",
  "snippet": "set_dir(${pin})",
  "type": "method",
  "detail": "MCP23017.set_dir: Set one pin's direction.",
  "info": "Set one pin's direction.\npin: Pin 0-15.\noutput: True for output (default), False for input."
 },
 {
  "label": "set_pullups",
  "snippet": "set_pullups(${pullup_mask})",
  "type": "method",
  "detail": "MCP23017.set_pullups: Set all 16 pull-ups.",
  "info": "Set all 16 pull-ups.\npullup_mask: 16-bit mask, bit n = pin n; 1 enables the 100 kOhm pull-up."
 },
 {
  "label": "set_pullup",
  "snippet": "set_pullup(${pin})",
  "type": "method",
  "detail": "MCP23017.set_pullup: Enable or disable one pin's pull-up.",
  "info": "Enable or disable one pin's pull-up.\npin: Pin 0-15.\nenable: True to enable (default)."
 },
 {
  "label": "write_port",
  "snippet": "write_port(${value})",
  "type": "method",
  "detail": "MCP23017.write_port: Write all 16 output levels.",
  "info": "Write all 16 output levels.\nvalue: 16-bit mask, bit n = pin n."
 },
 {
  "label": "read_port",
  "snippet": "read_port()",
  "type": "method",
  "detail": "MCP23017.read_port: Read all 16 pin levels.",
  "info": "Read all 16 pin levels.\nreturns: A 16-bit mask, bit n = pin n."
 },
 {
  "label": "set_pin",
  "snippet": "set_pin(${pin}, ${value})",
  "type": "method",
  "detail": "MCP23017.set_pin: Set one output pin, leaving the others unchanged.",
  "info": "Set one output pin, leaving the others unchanged.\npin: Pin 0-15.\nvalue: 0 or 1."
 },
 {
  "label": "read_pin",
  "snippet": "read_pin(${pin})",
  "type": "method",
  "detail": "MCP23017.read_pin: Read one pin.",
  "info": "Read one pin.\npin: Pin 0-15.\nreturns: 0 or 1."
 },
 {
  "label": "pin_mode",
  "snippet": "pin_mode(${pin})",
  "type": "method",
  "detail": "MCP23017.pin_mode: Set direction and pull-up of one pin in one call.",
  "info": "Set direction and pull-up of one pin in one call.\npin: Pin 0-15.\noutput: True for output (default), False for input.\npullup: True enables the pull-up. Default False."
 },
 {
  "label": "set_pwm_freq",
  "snippet": "set_pwm_freq(${freq_hz})",
  "type": "method",
  "detail": "PCA9685.set_pwm_freq: Set the PWM frequency for all channels.",
  "info": "Set the PWM frequency for all channels.\nfreq_hz: Frequency in hertz, greater than 0 (about 24-1526 Hz is reachable).\nreturns: The prescale value written."
 },
 {
  "label": "set_pwm",
  "snippet": "set_pwm(${channel})",
  "type": "method",
  "detail": "PCA9685.set_pwm: Set a channel's raw on/off counts.",
  "info": "Set a channel's raw on/off counts.\nchannel: Channel 0-15.\non: Count (0-4095) at which the output turns on. Default 0.\noff: Count (0-4095) at which it turns off. Default 0."
 },
 {
  "label": "set_duty",
  "snippet": "set_duty(${channel}, ${duty})",
  "type": "method",
  "detail": "PCA9685.set_duty: Set a channel's duty cycle.",
  "info": "Set a channel's duty cycle.\nchannel: Channel 0-15.\nduty: Duty cycle 0.0-1.0 (clamped)."
 },
 {
  "label": "write_u8",
  "snippet": "write_u8(${reg}, ${value})",
  "type": "method",
  "detail": "TCS34725.write_u8: Write one register.",
  "info": "Write one register.\nreg: Register address.\nvalue: Byte value, 0-255."
 },
 {
  "label": "read_u8",
  "snippet": "read_u8(${reg})",
  "type": "method",
  "detail": "TCS34725.read_u8: Read one register.",
  "info": "Read one register.\nreg: Register address.\nreturns: The byte read."
 },
 {
  "label": "read_words",
  "snippet": "read_words(${reg})",
  "type": "method",
  "detail": "TCS34725.read_words: Read consecutive 16-bit little-endian registers.",
  "info": "Read consecutive 16-bit little-endian registers.\nreg: First register address.\ncount: Number of words. Default 4.\nreturns: A list of unsigned 16-bit integers."
 },
 {
  "label": "enable",
  "snippet": "enable()",
  "type": "method",
  "detail": "TCS34725.enable: Power on the sensor and start the RGBC converter.",
  "info": "Power on the sensor and start the RGBC converter."
 },
 {
  "label": "disable",
  "snippet": "disable()",
  "type": "method",
  "detail": "TCS34725.disable: Power the sensor down.",
  "info": "Power the sensor down."
 },
 {
  "label": "set_integration_time",
  "snippet": "set_integration_time(${integration_ms})",
  "type": "method",
  "detail": "TCS34725.set_integration_time: Set the integration time.",
  "info": "Set the integration time.\nintegration_ms: Milliseconds, about 2.4-614.\nreturns: The ATIME register value written."
 },
 {
  "label": "set_gain",
  "snippet": "set_gain(${gain})",
  "type": "method",
  "detail": "TCS34725.set_gain: Set the analog gain.",
  "info": "Set the analog gain.\ngain: 1, 4, 16 or 60.\nreturns: The gain."
 },
 {
  "label": "read_rgbc",
  "snippet": "read_rgbc()",
  "type": "method",
  "detail": "TCS34725.read_rgbc: Wait one integration time and read the four channels.",
  "info": "Wait one integration time and read the four channels.\nreturns: ``(red, green, blue, clear)`` raw 16-bit counts."
 },
 {
  "label": "wake",
  "snippet": "wake()",
  "type": "method",
  "detail": "MPU6050.wake: Take the part out of sleep (10 ms wait).",
  "info": "Take the part out of sleep (10 ms wait)."
 },
 {
  "label": "set_ranges",
  "snippet": "set_ranges()",
  "type": "method",
  "detail": "MPU6050.set_ranges: Set the full-scale ranges.",
  "info": "Set the full-scale ranges.\naccel_range: g: 2, 4, 8 or 16. Default 2.\ngyro_range: deg/s: 250, 500, 1000 or 2000. Default 250.\nreturns: ``(accel_range, gyro_range)``."
 },
 {
  "label": "read_accel",
  "snippet": "read_accel()",
  "type": "method",
  "detail": "MPU6050.read_accel: Read acceleration.",
  "info": "Read acceleration.\nreturns: ``(ax, ay, az)`` in g."
 },
 {
  "label": "read_gyro",
  "snippet": "read_gyro()",
  "type": "method",
  "detail": "MPU6050.read_gyro: Read angular rate.",
  "info": "Read angular rate.\nreturns: ``(gx, gy, gz)`` in degrees per second."
 },
 {
  "label": "set_raw",
  "snippet": "set_raw(${code})",
  "type": "method",
  "detail": "MCP4725.set_raw: Write a raw code to the output register.",
  "info": "Write a raw code to the output register.\ncode: 0-4095 (masked to 12 bits).\nreturns: The code written."
 },
 {
  "label": "sleep",
  "snippet": "sleep()",
  "type": "method",
  "detail": "MCP4725.sleep: Put the DAC into power-down (output pulled down).",
  "info": "Put the DAC into power-down (output pulled down)."
 },
 {
  "label": "fill",
  "snippet": "fill(${col})",
  "type": "method",
  "detail": "SSD1306_I2C.fill: Fill the frame buffer.",
  "info": "Fill the frame buffer.\ncol: 0 for black, 1 for white."
 },
 {
  "label": "text",
  "snippet": "text(${s}, ${x}, ${y})",
  "type": "method",
  "detail": "SSD1306_I2C.text: Draw 8x8 text into the frame buffer.",
  "info": "Draw 8x8 text into the frame buffer.\ns: Text to draw.\nx: Left pixel.\ny: Top pixel.\ncol: 0 or 1. Default 1."
 },
 {
  "label": "pixel",
  "snippet": "pixel(${x}, ${y})",
  "type": "method",
  "detail": "SSD1306_I2C.pixel: Set one pixel in the frame buffer.",
  "info": "Set one pixel in the frame buffer.\nx: Column.\ny: Row.\ncol: 0 or 1. Default 1."
 },
 {
  "label": "show",
  "snippet": "show()",
  "type": "method",
  "detail": "SSD1306_I2C.show: Send the frame buffer to the display.",
  "info": "Send the frame buffer to the display."
 }
];
