"""Drivers for common I2C/SPI/1-Wire parts (``bb_devices.py`` on the device).
Pass a ``bugbuster.I2C``/``SPI`` bus object."""

class TMP102:
    """TI TMP102 I2C temperature sensor driver."""
    def __init__(self, i2c, addr=72): ...
    def read_celsius(self): ...

class BMP280:
    """Bosch BMP280 I2C pressure/temperature sensor driver."""
    def __init__(self, i2c, addr=118): ...
    def read(self): ...

class MCP3008:
    """Microchip MCP3008 SPI 10-bit ADC driver."""
    def __init__(self, spi, channels=8): ...
    def read(self, channel, single_ended=True): ...

class DS18B20:
    """Dallas/Maxim DS18B20 1-Wire temperature sensor."""
    def __init__(self, pin): ...
    def scan(self): ...
    def roms(self): ...
    def read_celsius(self, rom=None, wait_ms=750): ...
    def read_all(self, wait_ms=750): ...

class DS3231:
    """Maxim DS3231 RTC with temperature readback."""
    def __init__(self, i2c, addr=104): ...
    def status(self): ...
    def clear_osf(self): ...
    def temperature_c(self): ...
    def read_datetime(self): ...
    def set_datetime(self, year, month, day, weekday, hour, minute, second): ...

class BH1750:
    """ROHM BH1750 ambient light sensor."""
    def __init__(self, i2c, addr=35): ...
    def power_on(self): ...
    def power_down(self): ...
    def reset(self): ...
    def set_mtreg(self, mtreg): ...
    def read_lux(self, high_res=True, one_time=True, mtreg=69): ...

class AHT20:
    """Aosong AHT20 humidity and temperature sensor."""
    def __init__(self, i2c, addr=56): ...
    def reset(self): ...
    def initialize(self): ...
    def read(self): ...
    def read_temperature(self): ...
    def read_humidity(self): ...

class SHT31:
    """Sensirion SHT31 temperature and humidity sensor."""
    def __init__(self, i2c, addr=68): ...
    def soft_reset(self): ...
    def status(self): ...
    def read(self, repeatability='high', clock_stretch=False): ...

class BME280:
    """Bosch BME280 compensated temperature / pressure / humidity sensor."""
    def __init__(self, i2c, addr=118): ...
    def read(self): ...
    def read_raw(self): ...

class INA219:
    """TI INA219 current/power monitor."""
    def __init__(self, i2c, addr=64, shunt_ohms=0.1, max_expected_amps=2.0): ...
    def read_shunt_voltage(self): ...
    def read_bus_voltage(self): ...
    def read_current(self): ...
    def read_power(self): ...
    def read(self): ...

class ADS1115:
    """TI ADS1115 I2C ADC."""
    def __init__(self, i2c, addr=72): ...
    def read_raw(self, channel=0, pga=4.096, data_rate=128, continuous=False, differential=False): ...
    def read_voltage(self, channel=0, pga=4.096, data_rate=128, continuous=False, differential=False): ...

class MCP23017:
    """Microchip MCP23017 16-bit GPIO expander."""
    def __init__(self, i2c, addr=32): ...
    def write_reg(self, reg, value): ...
    def read_reg(self, reg): ...
    def set_direction(self, direction_mask): ...
    def set_dir(self, pin, output=True): ...
    def set_pullups(self, pullup_mask): ...
    def set_pullup(self, pin, enable=True): ...
    def write_port(self, value): ...
    def read_port(self): ...
    def set_pin(self, pin, value): ...
    def read_pin(self, pin): ...
    def pin_mode(self, pin, output=True, pullup=False): ...

class PCF8574:
    """NXP PCF8574 quasi-bidirectional I/O expander."""
    def __init__(self, i2c, addr=32, value=255): ...
    def write(self, value): ...
    def read(self): ...
    def set_pin(self, pin, value): ...
    def read_pin(self, pin): ...

class PCA9685:
    """NXP PCA9685 16-channel PWM controller."""
    def __init__(self, i2c, addr=64, osc_hz=25000000): ...
    def write_reg(self, reg, value): ...
    def read_reg(self, reg): ...
    def set_pwm_freq(self, freq_hz): ...
    def set_pwm(self, channel, on=0, off=0): ...
    def set_duty(self, channel, duty): ...

class TCS34725:
    """ams OSRAM TCS34725 RGBC color sensor."""
    def __init__(self, i2c, addr=41, integration_ms=50, gain=4): ...
    def write_u8(self, reg, value): ...
    def read_u8(self, reg): ...
    def read_words(self, reg, count=4): ...
    def enable(self): ...
    def disable(self): ...
    def set_integration_time(self, integration_ms): ...
    def set_gain(self, gain): ...
    def read_rgbc(self): ...

class MPU6050:
    """InvenSense MPU6050 6-axis IMU."""
    def __init__(self, i2c, addr=104, accel_range=2, gyro_range=250): ...
    def read_u8(self, reg): ...
    def write_u8(self, reg, value): ...
    def wake(self): ...
    def set_ranges(self, accel_range=2, gyro_range=250): ...
    def read_temperature(self): ...
    def read_accel(self): ...
    def read_gyro(self): ...
    def read(self): ...

class MCP4725:
    """Microchip MCP4725 12-bit I2C DAC."""
    def __init__(self, i2c, addr=96, vref=3.3): ...
    def set_raw(self, code): ...
    def set_voltage(self, voltage, vref=None): ...
    def sleep(self): ...
